/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view.employee;

import controller.credit.EmployeeCreditController;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.creditManagement.Employee;
import net.proteanit.sql.DbUtils;
import ui.view.credit.FinalCredit;
import util.Utilities;

/**
 *
 * @author HP
 */
public class ManageEmployees extends javax.swing.JFrame {

    private DefaultTableModel ManageEmployeesTableModel;
    boolean voucherValue = false;
    private HashMap<Integer, Employee> availableEmployees;

    /**
     * Creates new form ManageEmployees
     */
    public ManageEmployees() throws SQLException {
        initComponents();
        /*  jPanel4.setPreferredSize(new Dimension(600, 689));
         setSize(new Dimension(1500, 1500));*/
        this.ManageEmployeesTableModel = (DefaultTableModel) manageEmployeeTbl.getModel();

        manageEmployeeTbl.setModel(DbUtils.resultSetToTableModel(EmployeeCreditController.loadDetails()));

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void setEmployeeId() {

        int employeeIdNum = 0;
        try {
            employeeIdNum = EmployeeCreditController.getLastEmployeeId();
        } catch (SQLException ex) {
            employeeIdNum = 1;
        }

        addEmployeeIdTxt1.setText((Integer.toString(employeeIdNum + 1)));
    }

    public void addEmployee() throws SQLException {

        Object[] ob = {
            addEmployeeIdTxt1.getText(),
            addEmployeeFullNameTxt1.getText(),
            addEmployeePositionTxt.getText(),};
        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "manageEmployees");

        Employee employee = new Employee(Integer.parseInt(ob[0].toString()), ob[1].toString(), ob[2].toString(), true);

        EmployeeCreditController.addEmployee(employee);
        chngTblModel();

        addEmployeeIdTxt1.setText(null);
        addEmployeeFullNameTxt1.setText(null);
        addEmployeePositionTxt.setText(null);

    }

    public void editEmployeeDetails(int i) throws SQLException {

        EmployeeCreditController.getDetails(i);
        //      CreditCustomer creditCustomer = new CreditCustomer(ob[0].toString(),ob[1].toString(),Integer.parseInt(ob[2].toString()),ob[3].toString(),Integer.parseInt(ob[4].toString()),Integer.parseInt(ob[5].toString()));

        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "editEmployee");
        editEmployeeFullNameTxt2.setText(EmployeeCreditController.getDetails(i).getEmployeeName());
        editEmployeeIdTxt2.setText(Integer.toString(EmployeeCreditController.getDetails(i).getEmployeeId()));
        editEmployeePositionTxt1.setText(EmployeeCreditController.getDetails(i).getPosition());
        voucherValue = EmployeeCreditController.getDetails(i).isVoucherIssued();
    }

    public void setEditDetails() throws SQLException {
        int EmployeeId = 0;

        Object[] ob = {
            editEmployeeFullNameTxt2.getText(),
            editEmployeePositionTxt1.getText(),};

        try {
            EmployeeId = Integer.parseInt(editEmployeeIdTxt2.getText());

        } catch (NumberFormatException x) {
            Utilities.showMsgBox("System Error", "Error", JOptionPane.WARNING_MESSAGE);
        }

        Employee employee = new Employee(EmployeeId, ob[0].toString(), ob[1].toString(), voucherValue);

        EmployeeCreditController.setEditDetails(employee, Integer.parseInt(editEmployeeIdTxt2.getText()));
        chngTblModel();

        //CustomerCreditDetailsTableModel.removeRow(Integer.parseInt(editCustomerCoopIdTxt2.getText())-1);
        //  CustomerCreditDetailsTableModel.insertRow(Integer.parseInt(editCustomerCoopIdTxt2.getText())-1, ob);
        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "manageEmployees");
        //      CreditCustomer creditCustomer = new CreditCustomer(customerId,ob[1].toString(),ob[2].toString(),customerTele,ob[3].toString(),10000);

        EmployeeCreditController.setEditDetails(employee, EmployeeId);
        editEmployeeFullNameTxt2.setText(null);
        editEmployeeIdTxt2.setText(null);
        editEmployeePositionTxt1.setText(null);

    }

    public void deleteEmployeeDetails(int i) {

        try {
            EmployeeCreditController.deleteDeatils(i);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(FinalCredit.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            chngTblModel();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(FinalCredit.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void chngTblModel() throws SQLException {

        getManageEmployeeTbl().setModel(DbUtils.resultSetToTableModel(EmployeeCreditController.loadDetails()));

    }

    public void searchEmployeeDetails() throws SQLException {
        String s = employeeSearchEmployeeNameTxt.getText();
        EmployeeCreditController.searchDetails(s);
        CardLayout card = (CardLayout) subCardPanel.getLayout();
        card.show(subCardPanel, "employeeSearchResult");

        employeeSearchEmployeeIdrslt.setText(Integer.toString(EmployeeCreditController.searchDetails(s).getEmployeeId()));
        employeeSearchFullNamerslt.setText(EmployeeCreditController.searchDetails(s).getEmployeeName());
        employeeSearchPositionRslt.setText(EmployeeCreditController.searchDetails(s).getPosition());
        if (EmployeeCreditController.searchDetails(s).isVoucherIssued() == false) {
            jRadioButtonUsed.setSelected(true);
        } else {
            jRadioButtonExist.setSelected(true);
        }

        /*     employeeSearchEmployeeIdrslt.(false);
         employeeSearchFullNamerslt.setEnabled(false);
         employeeSearchPositionRslt.setEnabled(false);
         jRadioButtonExist.setEnabled(false);
         jRadioButtonUsed.setEnabled(false);*/
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        taskPaneSearchBtn = new javax.swing.JButton();
        jXTaskPane2 = new org.jdesktop.swingx.JXTaskPane();
        taskPaneManageEmployeesBtn = new javax.swing.JButton();
        taskPaneManageEmployeesBtn1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cardPanel = new javax.swing.JPanel();
        addEmployeePanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addEmployeeAddBtn = new org.jdesktop.swingx.JXButton();
        addEmployeeFullNameLbl2 = new javax.swing.JLabel();
        addEmployeeFullNameTxt1 = new javax.swing.JTextField();
        addEmployeePositionLbl = new javax.swing.JLabel();
        addEmployeePositionTxt = new javax.swing.JTextField();
        installmentPaymentLbl4 = new javax.swing.JLabel();
        addEmployeeIdLbl1 = new javax.swing.JLabel();
        addEmployeeIdTxt1 = new javax.swing.JTextField();
        subCardPanel = new javax.swing.JPanel();
        employeeSearch = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        employeeSearchEmployeeNameLbl = new javax.swing.JLabel();
        employeeSearchSearchBtn = new javax.swing.JButton();
        employeeSearchEmployeeNameTxt = new javax.swing.JTextField();
        installmentPaymentLbl3 = new javax.swing.JLabel();
        employeeSearchResultPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        employeeSearchEmployeeId = new javax.swing.JLabel();
        employeeSearchFullNameLbl = new javax.swing.JLabel();
        employeeSearchPosition = new javax.swing.JLabel();
        employeeSearchCredit = new javax.swing.JLabel();
        jRadioButtonExist = new javax.swing.JRadioButton();
        jRadioButtonUsed = new javax.swing.JRadioButton();
        employeeSearchEmployeeIdrslt = new javax.swing.JLabel();
        employeeSearchFullNamerslt = new javax.swing.JLabel();
        employeeSearchPositionRslt = new javax.swing.JLabel();
        installmentPaymentLbl2 = new javax.swing.JLabel();
        searchResultsOKBtn = new javax.swing.JButton();
        manageEmployees = new javax.swing.JPanel();
        manageEmployeesEditPanel = new org.jdesktop.swingx.JXPanel();
        edittEmployeeBtn1 = new org.jdesktop.swingx.JXButton();
        deleteEmployeeBtn1 = new org.jdesktop.swingx.JXButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        manageEmployeeTbl = new org.jdesktop.swingx.JXTable();
        employeeDetailsLbl = new javax.swing.JLabel();
        editEmployeePanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        editEmployeeSaveBtn1 = new org.jdesktop.swingx.JXButton();
        editEmployeeFullNameLbl3 = new javax.swing.JLabel();
        editEmployeeFullNameTxt2 = new javax.swing.JTextField();
        editEmployeePositionLbl1 = new javax.swing.JLabel();
        editEmployeePositionTxt1 = new javax.swing.JTextField();
        editEmployeeLbl = new javax.swing.JLabel();
        editEmployeeIdLbl2 = new javax.swing.JLabel();
        editEmployeeIdTxt2 = new javax.swing.JTextField();

        jButton1.setText("Add Employee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jXTaskPaneContainer1.setBackground(new java.awt.Color(102, 102, 102));
        jXTaskPaneContainer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jXTaskPane1.setBackground(new java.awt.Color(204, 204, 204));
        jXTaskPane1.setSpecial(true);
        jXTaskPane1.setTitle("Employee Search");
        jXTaskPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        taskPaneSearchBtn.setText("Search");
        taskPaneSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskPaneSearchBtnActionPerformed(evt);
            }
        });
        jXTaskPane1.getContentPane().add(taskPaneSearchBtn);

        jXTaskPaneContainer1.add(jXTaskPane1);

        jXTaskPane2.setBackground(new java.awt.Color(204, 204, 204));
        jXTaskPane2.setSpecial(true);
        jXTaskPane2.setTitle("Manage Employees");
        jXTaskPane2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        taskPaneManageEmployeesBtn.setText("Manage Employees");
        taskPaneManageEmployeesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskPaneManageEmployeesBtnActionPerformed(evt);
            }
        });
        jXTaskPane2.getContentPane().add(taskPaneManageEmployeesBtn);

        taskPaneManageEmployeesBtn1.setText("Add  Employee");
        taskPaneManageEmployeesBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskPaneManageEmployeesBtn1ActionPerformed(evt);
            }
        });
        jXTaskPane2.getContentPane().add(taskPaneManageEmployeesBtn1);
        taskPaneManageEmployeesBtn1.getAccessibleContext().setAccessibleName("AddEmployee");

        jXTaskPaneContainer1.add(jXTaskPane2);

        cardPanel.setLayout(new java.awt.CardLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        addEmployeeAddBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addEmployeeAddBtn.setText("Add");
        addEmployeeAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeAddBtnActionPerformed(evt);
            }
        });

        addEmployeeFullNameLbl2.setText("  Full Name");

        addEmployeeFullNameTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeFullNameTxt1ActionPerformed(evt);
            }
        });

        addEmployeePositionLbl.setText("  Position");

        addEmployeePositionTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeePositionTxtActionPerformed(evt);
            }
        });

        installmentPaymentLbl4.setBackground(new java.awt.Color(204, 204, 204));
        installmentPaymentLbl4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        installmentPaymentLbl4.setText("Add Employee");
        installmentPaymentLbl4.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        installmentPaymentLbl4.setOpaque(true);

        addEmployeeIdLbl1.setText("  Employee Id");

        addEmployeeIdTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeIdTxt1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(addEmployeeAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addEmployeeIdLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addEmployeePositionLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(addEmployeeFullNameLbl2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addEmployeeFullNameTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addEmployeeIdTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(addEmployeePositionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(9, 9, 9)))
                    .addComponent(installmentPaymentLbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(installmentPaymentLbl4)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEmployeeIdTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addEmployeeIdLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addEmployeeFullNameTxt1)
                    .addComponent(addEmployeeFullNameLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addEmployeePositionLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addEmployeePositionTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addEmployeeAddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout addEmployeePanelLayout = new javax.swing.GroupLayout(addEmployeePanel);
        addEmployeePanel.setLayout(addEmployeePanelLayout);
        addEmployeePanelLayout.setHorizontalGroup(
            addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeePanelLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );
        addEmployeePanelLayout.setVerticalGroup(
            addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeePanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(550, Short.MAX_VALUE))
        );

        cardPanel.add(addEmployeePanel, "addEmployee");

        subCardPanel.setLayout(new java.awt.CardLayout());

        employeeSearch.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        employeeSearch.setName("paymentHistory");

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        employeeSearchEmployeeNameLbl.setText("Employee Name");

        employeeSearchSearchBtn.setText("Search");
        employeeSearchSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeSearchSearchBtnActionPerformed(evt);
            }
        });

        employeeSearchEmployeeNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeSearchEmployeeNameTxtActionPerformed(evt);
            }
        });

        installmentPaymentLbl3.setBackground(new java.awt.Color(204, 204, 204));
        installmentPaymentLbl3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        installmentPaymentLbl3.setText("Search                            ");
        installmentPaymentLbl3.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        installmentPaymentLbl3.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(installmentPaymentLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(employeeSearchSearchBtn)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(employeeSearchEmployeeNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(215, 215, 215))))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(employeeSearchEmployeeNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(installmentPaymentLbl3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeeSearchEmployeeNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeeSearchEmployeeNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(employeeSearchSearchBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout employeeSearchLayout = new javax.swing.GroupLayout(employeeSearch);
        employeeSearch.setLayout(employeeSearchLayout);
        employeeSearchLayout.setHorizontalGroup(
            employeeSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeSearchLayout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        employeeSearchLayout.setVerticalGroup(
            employeeSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeSearchLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(581, Short.MAX_VALUE))
        );

        subCardPanel.add(employeeSearch, "employeeSearch");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        employeeSearchEmployeeId.setText("Employee Id");

        employeeSearchFullNameLbl.setText("Full Name");

        employeeSearchPosition.setText("Position");

        employeeSearchCredit.setText("Credit ");

        buttonGroup1.add(jRadioButtonExist);
        jRadioButtonExist.setText("Exist");

        buttonGroup1.add(jRadioButtonUsed);
        jRadioButtonUsed.setText("Used");

        installmentPaymentLbl2.setBackground(new java.awt.Color(204, 204, 204));
        installmentPaymentLbl2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        installmentPaymentLbl2.setText("Employee Details");
        installmentPaymentLbl2.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        installmentPaymentLbl2.setOpaque(true);

        searchResultsOKBtn.setText("OK");
        searchResultsOKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchResultsOKBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(installmentPaymentLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(employeeSearchCredit)
                                .addGap(138, 138, 138)
                                .addComponent(jRadioButtonExist))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(employeeSearchEmployeeId)
                                    .addGap(18, 18, 18)
                                    .addComponent(employeeSearchEmployeeIdrslt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(employeeSearchFullNameLbl)
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonUsed)
                                        .addComponent(employeeSearchFullNamerslt, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(employeeSearchPosition)
                                .addGap(18, 18, 18)
                                .addComponent(employeeSearchPositionRslt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 90, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchResultsOKBtn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(installmentPaymentLbl2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(employeeSearchEmployeeIdrslt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(employeeSearchEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(employeeSearchFullNamerslt, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(employeeSearchFullNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(employeeSearchPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(employeeSearchPositionRslt, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(employeeSearchCredit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonExist, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jRadioButtonUsed, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(searchResultsOKBtn)
                .addGap(5, 5, 5))
        );

        javax.swing.GroupLayout employeeSearchResultPanelLayout = new javax.swing.GroupLayout(employeeSearchResultPanel);
        employeeSearchResultPanel.setLayout(employeeSearchResultPanelLayout);
        employeeSearchResultPanelLayout.setHorizontalGroup(
            employeeSearchResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeSearchResultPanelLayout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );
        employeeSearchResultPanelLayout.setVerticalGroup(
            employeeSearchResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeSearchResultPanelLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(520, Short.MAX_VALUE))
        );

        subCardPanel.add(employeeSearchResultPanel, "employeeSearchResult");

        cardPanel.add(subCardPanel, "subCardPanel");

        manageEmployees.setLayout(new java.awt.GridBagLayout());

        manageEmployeesEditPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        edittEmployeeBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        edittEmployeeBtn1.setText("Edit");
        edittEmployeeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edittEmployeeBtn1ActionPerformed(evt);
            }
        });

        deleteEmployeeBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteEmployeeBtn1.setText("Delete");
        deleteEmployeeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageEmployeesEditPanelLayout = new javax.swing.GroupLayout(manageEmployeesEditPanel);
        manageEmployeesEditPanel.setLayout(manageEmployeesEditPanelLayout);
        manageEmployeesEditPanelLayout.setHorizontalGroup(
            manageEmployeesEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageEmployeesEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageEmployeesEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteEmployeeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edittEmployeeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        manageEmployeesEditPanelLayout.setVerticalGroup(
            manageEmployeesEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageEmployeesEditPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(edittEmployeeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteEmployeeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 1, 0, 70);
        manageEmployees.add(manageEmployeesEditPanel, gridBagConstraints);

        manageEmployeeTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmployeeId", "Full Name", "Position"
            }
        ));
        manageEmployeeTbl.setShowGrid(true);
        jScrollPane5.setViewportView(manageEmployeeTbl);
        if (manageEmployeeTbl.getColumnModel().getColumnCount() > 0) {
            manageEmployeeTbl.getColumnModel().getColumn(2).setResizable(false);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 717;
        gridBagConstraints.ipady = 492;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 11, 0);
        manageEmployees.add(jScrollPane5, gridBagConstraints);

        employeeDetailsLbl.setBackground(new java.awt.Color(204, 204, 204));
        employeeDetailsLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        employeeDetailsLbl.setOpaque(true);
        employeeDetailsLbl.setText("Employee Details");
        employeeDetailsLbl.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 169;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 74);
        manageEmployees.add(employeeDetailsLbl, gridBagConstraints);

        cardPanel.add(manageEmployees, "manageEmployees");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        editEmployeeSaveBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editEmployeeSaveBtn1.setText("Save");
        editEmployeeSaveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeSaveBtn1ActionPerformed(evt);
            }
        });

        editEmployeeFullNameLbl3.setText("  Full Name");

        editEmployeeFullNameTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeFullNameTxt2ActionPerformed(evt);
            }
        });

        editEmployeePositionLbl1.setText("  Position");

        editEmployeePositionTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeePositionTxt1ActionPerformed(evt);
            }
        });

        editEmployeeLbl.setBackground(new java.awt.Color(204, 204, 204));
        editEmployeeLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editEmployeeLbl.setText("Edit Employee");
        editEmployeeLbl.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        editEmployeeLbl.setOpaque(true);

        editEmployeeIdLbl2.setText("  Employee Id");

        editEmployeeIdTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEmployeeIdTxt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(editEmployeeSaveBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(editEmployeeIdLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editEmployeePositionLbl1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(editEmployeeFullNameLbl3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(editEmployeeFullNameTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editEmployeeIdTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(editEmployeePositionTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(9, 9, 9)))
                    .addComponent(editEmployeeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editEmployeeLbl)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEmployeeIdTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editEmployeeIdLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editEmployeeFullNameTxt2)
                    .addComponent(editEmployeeFullNameLbl3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editEmployeePositionLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editEmployeePositionTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editEmployeeSaveBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout editEmployeePanel1Layout = new javax.swing.GroupLayout(editEmployeePanel1);
        editEmployeePanel1.setLayout(editEmployeePanel1Layout);
        editEmployeePanel1Layout.setHorizontalGroup(
            editEmployeePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEmployeePanel1Layout.createSequentialGroup()
                .addGap(350, 350, 350)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );
        editEmployeePanel1Layout.setVerticalGroup(
            editEmployeePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editEmployeePanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(550, Short.MAX_VALUE))
        );

        cardPanel.add(editEmployeePanel1, "editEmployee");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeAddBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "manageEmployees");
        try {
            addEmployee();
        } catch (SQLException ex) {
            Logger.getLogger(ManageEmployees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addEmployeeAddBtnActionPerformed

    private void addEmployeeFullNameTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeFullNameTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmployeeFullNameTxt1ActionPerformed

    private void addEmployeePositionTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeePositionTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmployeePositionTxtActionPerformed

    private void edittEmployeeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edittEmployeeBtn1ActionPerformed
        // TODO add your handling code here:

        for (int i = 0; i <= getManageEmployeeTbl().getRowCount(); i++) {
            if (getManageEmployeeTbl().isRowSelected(i)) {

                try {
                    editEmployeeDetails(i + 1);
                } catch (SQLException ex) {
                    java.util.logging.Logger.getLogger(FinalCredit.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
            } else {
                if (i == getManageEmployeeTbl().getRowCount()) {
                    Utilities.showMsgBox("Select a row to edit details", "WARNING", JOptionPane.WARNING_MESSAGE);
                }
            }
        }

    }//GEN-LAST:event_edittEmployeeBtn1ActionPerformed

    private void deleteEmployeeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeBtn1ActionPerformed

        for (int i = 0; i <= getManageEmployeeTbl().getRowCount(); i++) {
            if (getManageEmployeeTbl().isRowSelected(i)) {

                deleteEmployeeDetails(Integer.parseInt(getManageEmployeeTbl().getValueAt(i, 0).toString()));
                break;
            } else {
                if (i == getManageEmployeeTbl().getRowCount() - 1) {
                    Utilities.showMsgBox("Select a row to delete", "WARNING", JOptionPane.WARNING_MESSAGE);
                }
            }
        } // TODO add your handling code here:
    }//GEN-LAST:event_deleteEmployeeBtn1ActionPerformed

    private void employeeSearchSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSearchSearchBtnActionPerformed
        try {
            // TODO add your handling code here:
            searchEmployeeDetails();
            employeeSearchEmployeeNameTxt.setText(null);
        } catch (SQLException ex) {
            Logger.getLogger(ManageEmployees.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_employeeSearchSearchBtnActionPerformed

    private void employeeSearchEmployeeNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeSearchEmployeeNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeSearchEmployeeNameTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "addEmployee");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void taskPaneManageEmployeesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskPaneManageEmployeesBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "manageEmployees");
    }//GEN-LAST:event_taskPaneManageEmployeesBtnActionPerformed

    private void taskPaneSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskPaneSearchBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "subCardPanel");
        CardLayout card1 = (CardLayout) subCardPanel.getLayout();
        card1.show(subCardPanel, "employeeSearch");

    }//GEN-LAST:event_taskPaneSearchBtnActionPerformed

    private void addEmployeeIdTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeIdTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addEmployeeIdTxt1ActionPerformed

    private void taskPaneManageEmployeesBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskPaneManageEmployeesBtn1ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "addEmployee");
        setEmployeeId();
    }//GEN-LAST:event_taskPaneManageEmployeesBtn1ActionPerformed

    private void editEmployeeSaveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeSaveBtn1ActionPerformed
        try {
            // TODO add your handling code here:
            setEditDetails();
        } catch (SQLException ex) {
            Logger.getLogger(ManageEmployees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editEmployeeSaveBtn1ActionPerformed

    private void editEmployeeFullNameTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeFullNameTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeeFullNameTxt2ActionPerformed

    private void editEmployeePositionTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeePositionTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeePositionTxt1ActionPerformed

    private void editEmployeeIdTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEmployeeIdTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editEmployeeIdTxt2ActionPerformed

    private void searchResultsOKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchResultsOKBtnActionPerformed
        // TODO add your handling code here:
        employeeSearchEmployeeIdrslt.setText(null);
        employeeSearchFullNamerslt.setText(null);
        employeeSearchPositionRslt.setText(null);

        jRadioButtonUsed.setSelected(false);

        jRadioButtonExist.setSelected(false);

        CardLayout card1 = (CardLayout) subCardPanel.getLayout();
        card1.show(subCardPanel, "employeeSearch");
        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "manageEmployees");

    }//GEN-LAST:event_searchResultsOKBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManageEmployees().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ManageEmployees.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton addEmployeeAddBtn;
    private javax.swing.JLabel addEmployeeFullNameLbl2;
    private javax.swing.JTextField addEmployeeFullNameTxt1;
    private javax.swing.JLabel addEmployeeIdLbl1;
    private javax.swing.JTextField addEmployeeIdTxt1;
    private javax.swing.JPanel addEmployeePanel;
    private javax.swing.JLabel addEmployeePositionLbl;
    private javax.swing.JTextField addEmployeePositionTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cardPanel;
    private org.jdesktop.swingx.JXButton deleteEmployeeBtn1;
    private javax.swing.JLabel editEmployeeFullNameLbl3;
    private javax.swing.JTextField editEmployeeFullNameTxt2;
    private javax.swing.JLabel editEmployeeIdLbl2;
    private javax.swing.JTextField editEmployeeIdTxt2;
    private javax.swing.JLabel editEmployeeLbl;
    private javax.swing.JPanel editEmployeePanel1;
    private javax.swing.JLabel editEmployeePositionLbl1;
    private javax.swing.JTextField editEmployeePositionTxt1;
    private org.jdesktop.swingx.JXButton editEmployeeSaveBtn1;
    private org.jdesktop.swingx.JXButton edittEmployeeBtn1;
    private javax.swing.JLabel employeeDetailsLbl;
    private javax.swing.JPanel employeeSearch;
    private javax.swing.JLabel employeeSearchCredit;
    private javax.swing.JLabel employeeSearchEmployeeId;
    private javax.swing.JLabel employeeSearchEmployeeIdrslt;
    private javax.swing.JLabel employeeSearchEmployeeNameLbl;
    private javax.swing.JTextField employeeSearchEmployeeNameTxt;
    private javax.swing.JLabel employeeSearchFullNameLbl;
    private javax.swing.JLabel employeeSearchFullNamerslt;
    private javax.swing.JLabel employeeSearchPosition;
    private javax.swing.JLabel employeeSearchPositionRslt;
    private javax.swing.JPanel employeeSearchResultPanel;
    private javax.swing.JButton employeeSearchSearchBtn;
    private javax.swing.JLabel installmentPaymentLbl2;
    private javax.swing.JLabel installmentPaymentLbl3;
    private javax.swing.JLabel installmentPaymentLbl4;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButtonExist;
    private javax.swing.JRadioButton jRadioButtonUsed;
    private javax.swing.JScrollPane jScrollPane5;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane2;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private org.jdesktop.swingx.JXTable manageEmployeeTbl;
    private javax.swing.JPanel manageEmployees;
    private org.jdesktop.swingx.JXPanel manageEmployeesEditPanel;
    private javax.swing.JButton searchResultsOKBtn;
    private javax.swing.JPanel subCardPanel;
    private javax.swing.JButton taskPaneManageEmployeesBtn;
    private javax.swing.JButton taskPaneManageEmployeesBtn1;
    private javax.swing.JButton taskPaneSearchBtn;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the ManageEmployeesTableModel
     */
    public DefaultTableModel getManageEmployeesTableModel() {
        return ManageEmployeesTableModel;
    }

    /**
     * @param ManageEmployeesTableModel the ManageEmployeesTableModel to set
     */
    public void setManageEmployeesTableModel(DefaultTableModel ManageEmployeesTableModel) {
        this.ManageEmployeesTableModel = ManageEmployeesTableModel;
    }

    /**
     * @return the manageEmployeeTbl
     */
    public org.jdesktop.swingx.JXTable getManageEmployeeTbl() {
        return manageEmployeeTbl;
    }

    /**
     * @param manageEmployeeTbl the manageEmployeeTbl to set
     */
    public void setManageEmployeeTbl(org.jdesktop.swingx.JXTable manageEmployeeTbl) {
        this.manageEmployeeTbl = manageEmployeeTbl;
    }
}
