package ui.view.supplier;

import controller.supplier.SupplierController;
import database.connector.DBConnection;
import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.text.PlainDocument;
import model.supplier.Supplier;
import util.EmailValidator;

public class SupplierInterface extends javax.swing.JInternalFrame {

    //
    // <editor-fold defaultstate="collapsed" desc="Variables">
    private static final org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(SupplierInterface.class);

    // </editor-fold>
    //
    //
    // <editor-fold defaultstate="collapsed" desc="Netbeans Generated">
    /**
     * Creates new form SupplierInterface
     */
    public SupplierInterface() {
        initComponents();
        initInterface();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSupplierID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtTPno = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnAddSupplier = new javax.swing.JButton();
        btnFindSupplier = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        dateRegDate = new org.jdesktop.swingx.JXDatePicker();
        dateCancelDate = new org.jdesktop.swingx.JXDatePicker();
        txtContactPerson = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);

        jLabel1.setText("Supplier ID");

        jLabel2.setText("Name");

        jLabel4.setText("Address");

        jLabel5.setText("TP no");

        jLabel6.setText("E - mail");

        jLabel7.setText("Fax");

        jLabel12.setText("Reg Date");

        jLabel13.setText("Cancel Date");

        txtSupplierID.setEditable(false);

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SupplierInterface.this.keyReleased(evt);
            }
        });

        txtTPno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SupplierInterface.this.keyReleased(evt);
            }
        });

        txtFax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SupplierInterface.this.keyReleased(evt);
            }
        });

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SupplierInterface.this.keyReleased(evt);
            }
        });

        jLabel14.setBackground(java.awt.SystemColor.textHighlight);
        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Supplier Details");
        jLabel14.setOpaque(true);

        btnAddSupplier.setText("New");
        btnAddSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSupplierActionPerformed(evt);
            }
        });

        btnFindSupplier.setText("Find");
        btnFindSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindSupplierActionPerformed(evt);
            }
        });

        btnAdd.setText("Add/Update");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtContactPerson.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SupplierInterface.this.keyReleased(evt);
            }
        });

        jLabel3.setText("Contact person");

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txtAddress.setRows(5);
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SupplierInterface.this.keyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txtAddress);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTPno, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                            .addComponent(txtContactPerson)
                            .addComponent(txtName)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(dateRegDate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFax, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                                    .addComponent(txtSupplierID))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(dateCancelDate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddSupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFindSupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {dateCancelDate, dateRegDate});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtContactPerson, txtFax, txtName, txtTPno});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnAddSupplier, btnClose, btnFindSupplier});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContactPerson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTPno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateRegDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(dateCancelDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnFindSupplier)
                    .addComponent(btnAddSupplier)
                    .addComponent(btnClose))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel4))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdd, btnAddSupplier, btnClose, btnFindSupplier});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {

        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierInterface().setVisible(true);
            }
        });
    }

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        newSupplier();
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void btnFindSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindSupplierActionPerformed
        findSupplier();
    }//GEN-LAST:event_btnFindSupplierActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        addUpdateSupplier();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        close();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void keyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyReleased
        contentVarifier(true);
    }//GEN-LAST:event_keyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnFindSupplier;
    private org.jdesktop.swingx.JXDatePicker dateCancelDate;
    private org.jdesktop.swingx.JXDatePicker dateRegDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtContactPerson;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSupplierID;
    private javax.swing.JTextField txtTPno;
    // End of variables declaration//GEN-END:variables

    // </editor-fold>
    //
    //
    // <editor-fold defaultstate="collapsed" desc="Functions">
    public Boolean contentVarifier(Boolean clr) {
        Boolean output = true;
        txtAddress.setBackground(Color.WHITE);
        txtContactPerson.setBackground(Color.WHITE);
        txtEmail.setBackground(Color.WHITE);
        txtFax.setBackground(Color.WHITE);
        txtName.setBackground(Color.WHITE);
        txtTPno.setBackground(Color.WHITE);

        if (!clr) {
            if ("".equals(txtAddress.getText())) {
                txtAddress.setBackground(Color.PINK);
                output = false;
            }
            if ("".equals(txtContactPerson.getText())) {
                txtContactPerson.setBackground(Color.PINK);
                output = false;
            }
            if ("".equals(txtEmail.getText()) || !EmailValidator.instance().validate(txtEmail.getText())) {
                txtEmail.setBackground(Color.PINK);
                output = false;
            }
            if ("".equals(txtFax.getText())) {
                txtFax.setBackground(Color.PINK);
                output = false;
            }
            if ("".equals(txtName.getText())) {
                txtName.setBackground(Color.PINK);
                output = false;
            }
            if ("".equals(txtTPno.getText())) {
                txtTPno.setBackground(Color.PINK);
                output = false;

            }
        }
        return output;
    }

    public void setSupplier(Supplier s) {
        txtSupplierID.setText(String.valueOf(s.getSupplerID()));
        txtName.setText(s.getName());
        txtContactPerson.setText(s.getContactPerson());
        txtAddress.setText(s.getAddress());
        txtTPno.setText(String.valueOf(s.getTelephoneNumber()));
        txtFax.setText(String.valueOf(s.getFax()));
        txtEmail.setText(s.getEmail());
        dateRegDate.setDate(s.getRagDate());
        dateCancelDate.setDate(s.getCancelDate());
    }

    private void addUpdateSupplier() {
        if (!contentVarifier(false)) {
            return;
        }
        try {
            Supplier currSupplier = new Supplier(
                    txtSupplierID.getText(),
                    txtName.getText(),
                    txtContactPerson.getText(),
                    txtAddress.getText(),
                    Integer.parseInt(txtTPno.getText()),
                    Integer.parseInt(txtFax.getText()),
                    txtEmail.getText(),
                    dateRegDate.getDate(),
                    dateCancelDate.getDate());
            if (SupplierController.supplierExists(txtSupplierID.getText())) {
                int val = util.Utilities.showButtonMsg("Do you want to update existing supplier?", "Alart", JOptionPane.YES_NO_OPTION);
                if (val == 0) {
                    // Update supplier SQL
                    SupplierController.updateSupplier(currSupplier);
                    util.Utilities.showMsgBox("Supplier details updated.", "Alart", JOptionPane.HEIGHT);
                } else {
                    util.Utilities.showMsgBox("Supplier update cancled.", "Alart", JOptionPane.HEIGHT);
                }
            } else {
                // Add new supplier
                SupplierController.addSupplier(currSupplier);
            }
        } catch (SQLException | NumberFormatException ex) {
            contentVarifier(false);
            util.Utilities.showMsgBox("The content for supplier is incorrect. Please recheck and enter correct information.", "Supplier Detail Entry Error", 0);
        }
        try {
            DBConnection.closeConnectionToDB();
        } catch (SQLException ex) {
            logger.error("Error Database is not conneted.");
            this.dispose();
        }
    }

    private void findSupplier() {
        SelectSupplier s = new SelectSupplier(this);
        ((JDesktopPane) this.getParent()).add(s);
        s.setVisible(true);
    }

    private void newSupplier() {
        try {
            txtSupplierID.setText(SupplierController.getNextSupplierID());
        } catch (SQLException ex) {
            logger.error("Error: " + ex.getMessage());
        }

        txtAddress.setText("");
        txtContactPerson.setText("");
        txtEmail.setText("");
        txtFax.setText("");
        txtName.setText("");
        txtTPno.setText("");
        dateRegDate.setDate(null);
        dateCancelDate.setDate(null);
    }

    private void initInterface() {
        ((PlainDocument) txtTPno.getDocument()).setDocumentFilter(new util.IntegerFilter());
        ((PlainDocument) txtFax.getDocument()).setDocumentFilter(new util.IntegerFilter());

        newSupplier();
    }

    private void close() {
        this.dispose();
    }

    // </editor-fold>
    //
}
