/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view.inventory;

import java.awt.CardLayout;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.text.PlainDocument;
import org.jdesktop.swingx.JXDatePicker;
import ui.handler.inventory.DiscountInterfaceHandler;
import util.DoubleFilter;
import util.PercentageFilter;
import util.Utilities;

/**
 *
 * @author Nadheesh
 */
public class DiscountInterface extends javax.swing.JInternalFrame {

    /**
     * Creates new form Discount
     */
    private DiscountInterfaceHandler handler;
    private boolean isCategoryDiscount;

    public DiscountInterface() throws SQLException {
        initComponents();
        handler = new DiscountInterfaceHandler(this);
        isCategoryDiscount = true;
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        startDate.setFormats(dateFormat);
        endDate.setFormats(dateFormat);
        handler.loadDepartmentCombo();
        
        //edited 8/15/2015 ========== Documentfilter added===========================
        ((PlainDocument) disText.getDocument()).setDocumentFilter(new PercentageFilter());
        ((PlainDocument) quantityText.getDocument()).setDocumentFilter(new DoubleFilter());
        
        //===========================================================================
        
        winRemoveBatch.setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        disType = new javax.swing.ButtonGroup();
        disAllowed = new javax.swing.ButtonGroup();
        winRemoveBatch = new javax.swing.JDialog();
        jXTitledPanel2 = new org.jdesktop.swingx.JXTitledPanel();
        removeBatchDiscount = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        catIdLabel = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        catNameLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        batchDisTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        winAddDiscount = new javax.swing.JDialog();
        setDiscountTitlePane = new org.jdesktop.swingx.JXTitledPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        setDiscountLayer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        disText = new javax.swing.JTextField();
        idText2 = new javax.swing.JComboBox();
        nameText2 = new javax.swing.JComboBox();
        startDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel5 = new javax.swing.JLabel();
        endDate = new org.jdesktop.swingx.JXDatePicker();
        label1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        proRadio = new javax.swing.JRadioButton();
        qtyRadio = new javax.swing.JRadioButton();
        quantityText = new javax.swing.JTextField();
        disToAll = new javax.swing.JRadioButton();
        disToMembers = new javax.swing.JRadioButton();
        idText1 = new javax.swing.JComboBox();
        label2 = new javax.swing.JLabel();
        nameText1 = new javax.swing.JComboBox();
        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        disTypeCombo = new javax.swing.JComboBox();
        cardPanel = new javax.swing.JPanel();
        categoryDiscount = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catDisTable = new javax.swing.JTable();
        batchDiscount = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        batchDisTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        disType.add(proRadio);
        disType.add(qtyRadio);

        winRemoveBatch.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        winRemoveBatch.setMinimumSize(new java.awt.Dimension(945, 488));
        winRemoveBatch.setModal(true);
        winRemoveBatch.setResizable(false);

        jXTitledPanel2.setTitleFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jXTitledPanel2.setMinimumSize(new java.awt.Dimension(930, 425));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        removeBatchDiscount.setBorder(dropShadowBorder1);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Category Name :");

        catIdLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        catIdLabel.setText(" ");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Category ID :");

        catNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        catNameLabel.setText(" ");

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        jScrollPane4.setBorder(dropShadowBorder2);

        batchDisTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Remove", "Product ID", "Proudct Name", "Batch ID", "Discount", "Start Date", "Finish Date", "Discount Type", "Quantity", "Members Only"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        batchDisTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(batchDisTable1);
        batchDisTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (batchDisTable1.getColumnModel().getColumnCount() > 0) {
            batchDisTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
            batchDisTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            batchDisTable1.getColumnModel().getColumn(2).setPreferredWidth(250);
            batchDisTable1.getColumnModel().getColumn(3).setPreferredWidth(100);
            batchDisTable1.getColumnModel().getColumn(4).setPreferredWidth(100);
            batchDisTable1.getColumnModel().getColumn(5).setPreferredWidth(150);
            batchDisTable1.getColumnModel().getColumn(6).setPreferredWidth(150);
            batchDisTable1.getColumnModel().getColumn(7).setPreferredWidth(200);
            batchDisTable1.getColumnModel().getColumn(8).setPreferredWidth(100);
            batchDisTable1.getColumnModel().getColumn(9).setPreferredWidth(100);
        }

        javax.swing.GroupLayout removeBatchDiscountLayout = new javax.swing.GroupLayout(removeBatchDiscount);
        removeBatchDiscount.setLayout(removeBatchDiscountLayout);
        removeBatchDiscountLayout.setHorizontalGroup(
            removeBatchDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeBatchDiscountLayout.createSequentialGroup()
                .addGroup(removeBatchDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(removeBatchDiscountLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(catIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(catNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(removeBatchDiscountLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        removeBatchDiscountLayout.setVerticalGroup(
            removeBatchDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removeBatchDiscountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(removeBatchDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(catIdLabel)
                    .addComponent(jLabel12)
                    .addComponent(catNameLabel))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton6.setText("Close");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Remove");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setText("Select All");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setText("Deselect All");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 491, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton6)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        javax.swing.GroupLayout jXTitledPanel2Layout = new javax.swing.GroupLayout(jXTitledPanel2.getContentContainer());
        jXTitledPanel2.getContentContainer().setLayout(jXTitledPanel2Layout);
        jXTitledPanel2Layout.setHorizontalGroup(
            jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBatchDiscount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jXTitledPanel2Layout.setVerticalGroup(
            jXTitledPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removeBatchDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout winRemoveBatchLayout = new javax.swing.GroupLayout(winRemoveBatch.getContentPane());
        winRemoveBatch.getContentPane().setLayout(winRemoveBatchLayout);
        winRemoveBatchLayout.setHorizontalGroup(
            winRemoveBatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winRemoveBatchLayout.createSequentialGroup()
                .addComponent(jXTitledPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        winRemoveBatchLayout.setVerticalGroup(
            winRemoveBatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winRemoveBatchLayout.createSequentialGroup()
                .addComponent(jXTitledPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
        );

        winAddDiscount.setMinimumSize(new java.awt.Dimension(776, 387));
        winAddDiscount.setModal(true);
        winAddDiscount.setResizable(false);

        setDiscountTitlePane.setTitleFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(588, 588, 588)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(1, 1, 1))
        );

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        setDiscountLayer.setBorder(dropShadowBorder3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Discount %");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Start Date");

        disText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        disText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        disText.setText("0.00");
        disText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disTextActionPerformed(evt);
            }
        });

        idText2.setEditable(true);
        idText2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idText2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        idText2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idText2ItemStateChanged(evt);
            }
        });
        idText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idText2ActionPerformed(evt);
            }
        });

        nameText2.setEditable(true);
        nameText2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameText2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        nameText2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nameText2ItemStateChanged(evt);
            }
        });

        startDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        startDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("End Date");

        endDate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        label1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label1.setText("Department");

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShowBottomShadow(false);
        dropShadowBorder4.setShowRightShadow(false);
        dropShadowBorder4.setShowTopShadow(true);
        jPanel4.setBorder(dropShadowBorder4);

        proRadio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        proRadio.setSelected(true);
        proRadio.setText("Promotional");
        proRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proRadioActionPerformed(evt);
            }
        });

        qtyRadio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        qtyRadio.setText("Quantity");
        qtyRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyRadioActionPerformed(evt);
            }
        });

        quantityText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        quantityText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        quantityText.setText("0.00");
        quantityText.setEnabled(false);
        quantityText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTextActionPerformed(evt);
            }
        });

        disAllowed.add(disToAll);
        disToAll.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        disToAll.setSelected(true);
        disToAll.setText("All");
        disToAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disToAllActionPerformed(evt);
            }
        });

        disAllowed.add(disToMembers);
        disToMembers.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        disToMembers.setText("Only Members");
        disToMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disToMembersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(disToAll)
                            .addComponent(disToMembers))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(proRadio)
                            .addComponent(qtyRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(quantityText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(proRadio)
                    .addComponent(disToAll))
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quantityText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(disToMembers)
                        .addComponent(qtyRadio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7))
        );

        idText1.setEditable(true);
        idText1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idText1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        idText1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                idText1ItemStateChanged(evt);
            }
        });
        idText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idText1ActionPerformed(evt);
            }
        });

        label2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        label2.setText("Category");

        nameText1.setEditable(true);
        nameText1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameText1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        nameText1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nameText1ItemStateChanged(evt);
            }
        });
        nameText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameText1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout setDiscountLayerLayout = new javax.swing.GroupLayout(setDiscountLayer);
        setDiscountLayer.setLayout(setDiscountLayerLayout);
        setDiscountLayerLayout.setHorizontalGroup(
            setDiscountLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(setDiscountLayerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(setDiscountLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(setDiscountLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setDiscountLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(disText)
                        .addComponent(startDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(endDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idText2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idText1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(setDiscountLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameText2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameText1, 0, 189, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        setDiscountLayerLayout.setVerticalGroup(
            setDiscountLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setDiscountLayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(setDiscountLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(idText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setDiscountLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2)
                    .addComponent(nameText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setDiscountLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(disText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setDiscountLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setDiscountLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setDiscountLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(setDiscountLayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout setDiscountTitlePaneLayout = new javax.swing.GroupLayout(setDiscountTitlePane.getContentContainer());
        setDiscountTitlePane.getContentContainer().setLayout(setDiscountTitlePaneLayout);
        setDiscountTitlePaneLayout.setHorizontalGroup(
            setDiscountTitlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        setDiscountTitlePaneLayout.setVerticalGroup(
            setDiscountTitlePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setDiscountTitlePaneLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout winAddDiscountLayout = new javax.swing.GroupLayout(winAddDiscount.getContentPane());
        winAddDiscount.getContentPane().setLayout(winAddDiscountLayout);
        winAddDiscountLayout.setHorizontalGroup(
            winAddDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winAddDiscountLayout.createSequentialGroup()
                .addComponent(setDiscountTitlePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        winAddDiscountLayout.setVerticalGroup(
            winAddDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winAddDiscountLayout.createSequentialGroup()
                .addComponent(setDiscountTitlePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximumSize(new java.awt.Dimension(1155, 545));
        setMinimumSize(new java.awt.Dimension(1155, 545));

        jXTitledPanel1.setTitle("Discounts");
        jXTitledPanel1.setTitleFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Discount Policy");

        disTypeCombo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        disTypeCombo.setMaximumRowCount(2);
        disTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Category Wise", "Batch Wise" }));
        disTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disTypeComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(disTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(837, 837, 837))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(disTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder5 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder5.setShowLeftShadow(true);
        dropShadowBorder5.setShowTopShadow(true);
        cardPanel.setBorder(dropShadowBorder5);
        cardPanel.setMaximumSize(new java.awt.Dimension(1116, 395));
        cardPanel.setMinimumSize(new java.awt.Dimension(1116, 395));
        cardPanel.setLayout(new java.awt.CardLayout());

        categoryDiscount.setMaximumSize(new java.awt.Dimension(1106, 385));
        categoryDiscount.setName(""); // NOI18N
        categoryDiscount.setPreferredSize(new java.awt.Dimension(1106, 385));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cateogory Discount");

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder6 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder6.setShowLeftShadow(true);
        dropShadowBorder6.setShowTopShadow(true);
        jScrollPane1.setBorder(dropShadowBorder6);

        catDisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Discount ID", "Catogery Name", "Department", "Discount", "Start Date", "End date", "Discount Type", "Quantity", "Members Only"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        catDisTable.setColumnSelectionAllowed(true);
        catDisTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(catDisTable);
        catDisTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (catDisTable.getColumnModel().getColumnCount() > 0) {
            catDisTable.getColumnModel().getColumn(0).setPreferredWidth(150);
            catDisTable.getColumnModel().getColumn(1).setPreferredWidth(250);
            catDisTable.getColumnModel().getColumn(2).setPreferredWidth(250);
            catDisTable.getColumnModel().getColumn(3).setPreferredWidth(150);
            catDisTable.getColumnModel().getColumn(4).setPreferredWidth(150);
            catDisTable.getColumnModel().getColumn(5).setPreferredWidth(150);
            catDisTable.getColumnModel().getColumn(6).setPreferredWidth(200);
            catDisTable.getColumnModel().getColumn(7).setPreferredWidth(100);
            catDisTable.getColumnModel().getColumn(8).setPreferredWidth(100);
        }

        javax.swing.GroupLayout categoryDiscountLayout = new javax.swing.GroupLayout(categoryDiscount);
        categoryDiscount.setLayout(categoryDiscountLayout);
        categoryDiscountLayout.setHorizontalGroup(
            categoryDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryDiscountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(categoryDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE))
                .addContainerGap())
        );
        categoryDiscountLayout.setVerticalGroup(
            categoryDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(categoryDiscountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardPanel.add(categoryDiscount, "categoryDiscount");

        batchDiscount.setMaximumSize(new java.awt.Dimension(1106, 385));
        batchDiscount.setPreferredSize(new java.awt.Dimension(1106, 385));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder7 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder7.setShowLeftShadow(true);
        dropShadowBorder7.setShowTopShadow(true);
        jScrollPane2.setBorder(dropShadowBorder7);

        batchDisTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Proudct Name", "Batch ID", "Discount", "Start Date", "Finish Date", "Discount Type", "Quantity", "Members Only"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        batchDisTable.setCellSelectionEnabled(true);
        batchDisTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(batchDisTable);
        batchDisTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (batchDisTable.getColumnModel().getColumnCount() > 0) {
            batchDisTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            batchDisTable.getColumnModel().getColumn(1).setPreferredWidth(250);
            batchDisTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            batchDisTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            batchDisTable.getColumnModel().getColumn(4).setPreferredWidth(150);
            batchDisTable.getColumnModel().getColumn(5).setPreferredWidth(150);
            batchDisTable.getColumnModel().getColumn(6).setPreferredWidth(200);
            batchDisTable.getColumnModel().getColumn(7).setPreferredWidth(150);
            batchDisTable.getColumnModel().getColumn(8).setPreferredWidth(150);
        }

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Batch Discount");

        javax.swing.GroupLayout batchDiscountLayout = new javax.swing.GroupLayout(batchDiscount);
        batchDiscount.setLayout(batchDiscountLayout);
        batchDiscountLayout.setHorizontalGroup(
            batchDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(batchDiscountLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(batchDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        batchDiscountLayout.setVerticalGroup(
            batchDiscountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, batchDiscountLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardPanel.add(batchDiscount, "batchDiscount");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Net loss");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("New Profit");

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setText("Close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Remove ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("New Discount");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(760, 760, 760)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jXTitledPanel1Layout = new javax.swing.GroupLayout(jXTitledPanel1.getContentContainer());
        jXTitledPanel1.getContentContainer().setLayout(jXTitledPanel1Layout);
        jXTitledPanel1Layout.setHorizontalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jXTitledPanel1Layout.setVerticalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTitledPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jXTitledPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disTypeComboActionPerformed

        if (disTypeCombo.getSelectedItem().equals("Category Wise")) {

            try {
                //set category discount layout
                ((CardLayout) cardPanel.getLayout()).show(cardPanel, "categoryDiscount");
                handler.loadTableWithCategoryDiscount();
                //
            } catch (SQLException ex) {
                Logger.getLogger(DiscountInterface.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else if (disTypeCombo.getSelectedItem().equals("Batch Wise")) {

            //set layout
            ((CardLayout) cardPanel.getLayout()).show(cardPanel, "batchDiscount");
            try {
                handler.loadTableWithBatchDiscount();
            } catch (SQLException ex) {
                Logger.getLogger(DiscountInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
            //

        }

    }//GEN-LAST:event_disTypeComboActionPerformed

    private void disTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disTextActionPerformed

    private void quantityTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTextActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void startDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateActionPerformed

    private void proRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proRadioActionPerformed
        if (proRadio.isSelected()) {
            quantityText.setEnabled(false);
            quantityText.setText("0.00");
        }
    }//GEN-LAST:event_proRadioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        winAddDiscount.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void qtyRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyRadioActionPerformed
        if (qtyRadio.isSelected()) {
            quantityText.setEnabled(true);
        }
    }//GEN-LAST:event_qtyRadioActionPerformed

    private void disToAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disToAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disToAllActionPerformed

    private void disToMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disToMembersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disToMembersActionPerformed

    private void idText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idText1ActionPerformed

    private void idText1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idText1ItemStateChanged
        int index = idText1.getSelectedIndex();
        if (nameText1.getSelectedIndex() != index) {

            nameText1.setSelectedIndex(index);

            if (index > 0) {
                if (isCategoryDiscount) {
                    try {
                        handler.loadCategories(index);
                    } catch (SQLException ex) {
                        Logger.getLogger(ManageDepartment.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    try {
                        handler.loadBatches(index);
                    } catch (SQLException ex) {
                        Logger.getLogger(DiscountInterface.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
    }//GEN-LAST:event_idText1ItemStateChanged

    private void nameText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameText1ActionPerformed

    private void nameText1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nameText1ItemStateChanged
        int index = nameText1.getSelectedIndex();
        if (idText1.getSelectedIndex() != index) {

            idText1.setSelectedIndex(index);

            if (index > 0) {
                try {
                    handler.loadCategories(index);
                } catch (SQLException ex) {
                    Logger.getLogger(ManageDepartment.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_nameText1ItemStateChanged

    private void idText2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_idText2ItemStateChanged
        if (isCategoryDiscount) {
            int index = idText2.getSelectedIndex();
            if (nameText2.getSelectedIndex() != index) {
                nameText2.setSelectedIndex(index);
            }
        }
    }//GEN-LAST:event_idText2ItemStateChanged

    private void nameText2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nameText2ItemStateChanged
        int index = nameText2.getSelectedIndex();
        if (idText2.getSelectedIndex() != index) {
            idText2.setSelectedIndex(index);
        }
    }//GEN-LAST:event_nameText2ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (disTypeCombo.getSelectedItem().equals("Category Wise")) {
            try {
                handler.saveCategoryDiscount();
            } catch (SQLException ex) {
                Logger.getLogger(DiscountInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (disTypeCombo.getSelectedItem().equals("Batch Wise")) {
            try {
                handler.saveBatchDiscount();
            } catch (SQLException ex) {
                Logger.getLogger(DiscountInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void idText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idText2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (disTypeCombo.getSelectedItem().equals("Category Wise")) {

            isCategoryDiscount = true;
            label1.setText("Department");
            label2.setText("Category");
            setDiscountTitlePane.setTitle("Set Category Discount");
            nameText2.setVisible(true);
            clearFields();

            try {

                handler.loadDepartmentCombo();
                winAddDiscount.setLocationRelativeTo(this);
                winAddDiscount.setVisible(true);

            } catch (SQLException ex) {
                Logger.getLogger(DiscountInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (disTypeCombo.getSelectedItem().equals("Batch Wise")) {

            isCategoryDiscount = false;
            label1.setText("Product");
            label2.setText("Batch");
            setDiscountTitlePane.setTitle("Set Batch Discount");
            nameText2.setVisible(false);
            clearFields();

            try {

                handler.loadProductCombo();
                winAddDiscount.setLocationRelativeTo(this);
                winAddDiscount.setVisible(true);

            } catch (SQLException ex) {
                Logger.getLogger(DiscountInterface.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        winRemoveBatch.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            handler.removeSelectedBatchDiscounts();
            Utilities.ShowCompleteMsg(this, "Discount Remove Successfull");
        } catch (SQLException ex) {
            Logger.getLogger(DiscountInterface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        for (int i = 0; i < batchDisTable1.getRowCount(); i++) {
            batchDisTable1.setValueAt(true, i, 0);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        for (int i = 0; i < batchDisTable1.getRowCount(); i++) {
            batchDisTable1.setValueAt(false, i, 0);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        if (disTypeCombo.getSelectedItem().equals("Category Wise")) {
            try {
                handler.removeCategoryDiscount();
            } catch (SQLException ex) {
                Logger.getLogger(DiscountInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (disTypeCombo.getSelectedItem().equals("Batch Wise")) {
            try {
                handler.removeBatchDiscount();
            } catch (SQLException ex) {
                Logger.getLogger(DiscountInterface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    public JXDatePicker getEndDate() {
        return endDate;
    }

    public JTextField getDisText() {
        return disText;
    }

    public JComboBox getDisTypeCombo() {
        return disTypeCombo;
    }

    public JComboBox getIdText1() {
        return idText1;
    }

    public JComboBox getIdText2() {
        return idText2;
    }

    public JComboBox getNameText1() {
        return nameText1;
    }

    public JComboBox getNameText2() {
        return nameText2;
    }

    public JRadioButton getProRadio() {
        return proRadio;
    }

    public void getDiscountError(String text) {
        JOptionPane.showMessageDialog(this, text);
    }

    public JRadioButton getQtyRadio() {
        return qtyRadio;
    }

    public JTextField getQuantityText() {
        return quantityText;
    }

    public JXDatePicker getStartDate() {
        return startDate;
    }

    public JRadioButton getDisToAll() {
        return disToAll;
    }

    public JRadioButton getDisToMembers() {
        return disToMembers;
    }

    public JDialog getWinAddDiscount() {
        return winAddDiscount;
    }

    public JTable getCatDisTable() {
        return catDisTable;
    }

    public JTable getBatchDisTable() {
        return batchDisTable;
    }

    public JTable getRemovetBatchDisTable() {
        return batchDisTable1;
    }

    public JDialog getWinRemoveBatch() {
        return winRemoveBatch;
    }

    public JLabel getCatIdLabel() {
        return catIdLabel;
    }

    public JLabel getCatNameLabel() {
        return catNameLabel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiscountInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiscountInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiscountInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiscountInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(DiscountInterface.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DiscountInterface().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DiscountInterface.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable batchDisTable;
    private javax.swing.JTable batchDisTable1;
    private javax.swing.JPanel batchDiscount;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JTable catDisTable;
    private javax.swing.JLabel catIdLabel;
    private javax.swing.JLabel catNameLabel;
    private javax.swing.JPanel categoryDiscount;
    private javax.swing.ButtonGroup disAllowed;
    private javax.swing.JTextField disText;
    private javax.swing.JRadioButton disToAll;
    private javax.swing.JRadioButton disToMembers;
    private javax.swing.ButtonGroup disType;
    private javax.swing.JComboBox disTypeCombo;
    private org.jdesktop.swingx.JXDatePicker endDate;
    private javax.swing.JComboBox idText1;
    private javax.swing.JComboBox idText2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JComboBox nameText1;
    private javax.swing.JComboBox nameText2;
    private javax.swing.JRadioButton proRadio;
    private javax.swing.JRadioButton qtyRadio;
    private javax.swing.JTextField quantityText;
    private javax.swing.JPanel removeBatchDiscount;
    private javax.swing.JPanel setDiscountLayer;
    private org.jdesktop.swingx.JXTitledPanel setDiscountTitlePane;
    private org.jdesktop.swingx.JXDatePicker startDate;
    private javax.swing.JDialog winAddDiscount;
    private javax.swing.JDialog winRemoveBatch;
    // End of variables declaration//GEN-END:variables

    public void clearFields() {

        idText1.removeAllItems();
        idText2.removeAllItems();
        idText1.addItem("");
        idText2.addItem("");

        idText1.setSelectedIndex(0);
        idText2.setSelectedIndex(0);

        nameText1.removeAllItems();
        nameText2.removeAllItems();
        nameText1.addItem("");
        nameText2.addItem("");

        nameText1.setSelectedIndex(0);
        nameText2.setSelectedIndex(0);

    }
}
