/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view.inventory;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import ui.handler.inventory.ManageDepartmentHandler;

/**
 *
 * @author Nadheesh
 */
public class ManageDepartment extends javax.swing.JInternalFrame {

    private String idString;
    private String nameString;
    private String[] colTitle;
    private Class[] colTypes;
    private int[] colSizes;
    private int colCount;
    private String tableName;
    private ManageDepartmentHandler handler;
    private boolean isEditing;

    /**
     *
     * Creates new form AddDepartment
     */
    public ManageDepartment() throws SQLException {

        colCount = 6;
        colSizes = new int[]{100, 100, 200, 100, 125, 125};
        colTitle = new String[]{"Category ID", "Category Name", "Descripton", "Discount", "Discount Start Date", "Discount Finish Date"};
        colTypes = new Class[]{java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class};
        idString = "Department";
        nameString = "Department";
        tableName = "Categories";
        handler = new ManageDepartmentHandler(this);
        isEditing = false;
        initComponents();

        jXTitledPanel1.setTitle("Manage Departments");

        //----------------------------------------------------------------------------------------
        handler.loadDepartmentCombo();

        //--------------------------------------------------------------------------------------
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateDepartment = new javax.swing.JFrame();
        fullPanel1 = new javax.swing.JPanel();
        updateDepPanel = new org.jdesktop.swingx.JXTitledPanel();
        enterPanel2 = new javax.swing.JPanel();
        idLabel2 = new javax.swing.JLabel();
        nameLabel4 = new javax.swing.JLabel();
        depIdText = new javax.swing.JTextField();
        depNameText = new javax.swing.JTextField();
        buttonPanel2 = new javax.swing.JPanel();
        saveDepB = new javax.swing.JButton();
        closeB3 = new javax.swing.JButton();
        updateCategory = new javax.swing.JFrame();
        catTitlePanel = new org.jdesktop.swingx.JXTitledPanel();
        enterPanel1 = new javax.swing.JPanel();
        idLabel1 = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        catIdText = new javax.swing.JTextField();
        catNameText = new javax.swing.JTextField();
        idComment = new javax.swing.JLabel();
        nameLabel3 = new javax.swing.JLabel();
        CatDescText = new javax.swing.JTextField();
        buttonPanel1 = new javax.swing.JPanel();
        addB2 = new javax.swing.JButton();
        closeB2 = new javax.swing.JButton();
        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        depIdCombo = new javax.swing.JComboBox();
        depNameCombo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addB = new javax.swing.JButton();
        editB = new javax.swing.JButton();
        removeB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        saveB = new javax.swing.JButton();
        closeB = new javax.swing.JButton();
        clearB = new javax.swing.JButton();

        updateDepartment.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        updateDepartment.setMinimumSize(new java.awt.Dimension(401, 213));
        updateDepartment.setUndecorated(true);
        updateDepartment.setResizable(false);

        fullPanel1.setPreferredSize(new java.awt.Dimension(775, 319));

        updateDepPanel.setTitle("Add Department");
        updateDepPanel.setTitleFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        enterPanel2.setBorder(dropShadowBorder1);

        idLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idLabel2.setText("Department ID");

        nameLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameLabel4.setText("Department Name");

        depIdText.setBackground(new java.awt.Color(240, 240, 240));
        depIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depIdTextActionPerformed(evt);
            }
        });

        depNameText.setText("  ");
        depNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depNameTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enterPanel2Layout = new javax.swing.GroupLayout(enterPanel2);
        enterPanel2.setLayout(enterPanel2Layout);
        enterPanel2Layout.setHorizontalGroup(
            enterPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterPanel2Layout.createSequentialGroup()
                        .addComponent(idLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(depIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterPanel2Layout.createSequentialGroup()
                        .addComponent(nameLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        enterPanel2Layout.setVerticalGroup(
            enterPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(enterPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        saveDepB.setText("Save");
        saveDepB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDepBActionPerformed(evt);
            }
        });

        closeB3.setText("Cancel");
        closeB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeB3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanel2Layout = new javax.swing.GroupLayout(buttonPanel2);
        buttonPanel2.setLayout(buttonPanel2Layout);
        buttonPanel2Layout.setHorizontalGroup(
            buttonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(saveDepB, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeB3))
        );
        buttonPanel2Layout.setVerticalGroup(
            buttonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(buttonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveDepB)
                    .addComponent(closeB3))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout updateDepPanelLayout = new javax.swing.GroupLayout(updateDepPanel.getContentContainer());
        updateDepPanel.getContentContainer().setLayout(updateDepPanelLayout);
        updateDepPanelLayout.setHorizontalGroup(
            updateDepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateDepPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateDepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        updateDepPanelLayout.setVerticalGroup(
            updateDepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateDepPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout fullPanel1Layout = new javax.swing.GroupLayout(fullPanel1);
        fullPanel1.setLayout(fullPanel1Layout);
        fullPanel1Layout.setHorizontalGroup(
            fullPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateDepPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fullPanel1Layout.setVerticalGroup(
            fullPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateDepPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout updateDepartmentLayout = new javax.swing.GroupLayout(updateDepartment.getContentPane());
        updateDepartment.getContentPane().setLayout(updateDepartmentLayout);
        updateDepartmentLayout.setHorizontalGroup(
            updateDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        updateDepartmentLayout.setVerticalGroup(
            updateDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, Short.MAX_VALUE)
        );

        updateCategory.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        updateCategory.setMinimumSize(new java.awt.Dimension(484, 214));
        updateCategory.setUndecorated(true);
        updateCategory.setResizable(false);

        catTitlePanel.setTitle("Add Category");
        catTitlePanel.setTitleFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        enterPanel1.setBorder(dropShadowBorder2);

        idLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idLabel1.setText("Category ID");

        nameLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameLabel2.setText("Category Name");

        catIdText.setEditable(false);
        catIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catIdTextActionPerformed(evt);
            }
        });

        catNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catNameTextActionPerformed(evt);
            }
        });

        idComment.setText("  ");

        nameLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameLabel3.setText("Description");

        CatDescText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatDescTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enterPanel1Layout = new javax.swing.GroupLayout(enterPanel1);
        enterPanel1.setLayout(enterPanel1Layout);
        enterPanel1Layout.setHorizontalGroup(
            enterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enterPanel1Layout.createSequentialGroup()
                        .addComponent(nameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CatDescText))
                    .addGroup(enterPanel1Layout.createSequentialGroup()
                        .addComponent(nameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(catNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(enterPanel1Layout.createSequentialGroup()
                        .addGroup(enterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(enterPanel1Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(catIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idComment, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                .addContainerGap())
        );
        enterPanel1Layout.setVerticalGroup(
            enterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idComment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(enterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(enterPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CatDescText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        addB2.setText("Save");
        addB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addB2ActionPerformed(evt);
            }
        });

        closeB2.setText("Cancel");
        closeB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeB2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanel1Layout = new javax.swing.GroupLayout(buttonPanel1);
        buttonPanel1.setLayout(buttonPanel1Layout);
        buttonPanel1Layout.setHorizontalGroup(
            buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addB2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeB2)
                .addContainerGap())
        );
        buttonPanel1Layout.setVerticalGroup(
            buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(buttonPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addB2)
                    .addComponent(closeB2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout catTitlePanelLayout = new javax.swing.GroupLayout(catTitlePanel.getContentContainer());
        catTitlePanel.getContentContainer().setLayout(catTitlePanelLayout);
        catTitlePanelLayout.setHorizontalGroup(
            catTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(catTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        catTitlePanelLayout.setVerticalGroup(
            catTitlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catTitlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout updateCategoryLayout = new javax.swing.GroupLayout(updateCategory.getContentPane());
        updateCategory.getContentPane().setLayout(updateCategoryLayout);
        updateCategoryLayout.setHorizontalGroup(
            updateCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        updateCategoryLayout.setVerticalGroup(
            updateCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catTitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jXTitledPanel1.setTitleFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        jPanel1.setBorder(dropShadowBorder3);
        jPanel1.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText(idString+ " "+ "ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText(nameString+ " "+ "Name");

        jLabel3.setText("  ");

        depIdCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        depIdCombo.setAutoscrolls(true);
        depIdCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                depIdComboItemStateChanged(evt);
            }
        });
        depIdCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                depIdComboPopupMenuWillBecomeVisible(evt);
            }
        });
        depIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depIdComboActionPerformed(evt);
            }
        });

        depNameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        depNameCombo.setAutoscrolls(true);
        depNameCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                depNameComboPopupMenuWillBecomeVisible(evt);
            }
        });
        depNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depNameComboActionPerformed(evt);
            }
        });

        jButton2.setText("New Entry");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Edit Department");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Remove");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depIdCombo, 0, 244, Short.MAX_VALUE)
                    .addComponent(depNameCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(depIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(depNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Update "+ tableName, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));

        addB.setText("New Entry");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        editB.setText("Edit Category");

        removeB.setText("Remove");
        removeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(addB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addB)
                    .addComponent(editB)
                    .addComponent(removeB)))
        );

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShowLeftShadow(true);
        dropShadowBorder4.setShowTopShadow(true);
        jScrollPane1.setBorder(dropShadowBorder4);

        categoryTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            colTitle

        ) {
            Class[] types = colTypes;
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        categoryTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        categoryTable.setDragEnabled(true);
        categoryTable.setFillsViewportHeight(true);
        categoryTable.setFocusCycleRoot(true);
        jScrollPane1.setViewportView(categoryTable);
        categoryTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (categoryTable.getColumnModel().getColumnCount() > 0) {
            for (int i=0; i<colCount; i++){
                categoryTable.getColumnModel().getColumn(i).setMinWidth(60);
                categoryTable.getColumnModel().getColumn(i).setPreferredWidth(colSizes[i]);
            }
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        saveB.setText("Save");

        closeB.setText("Close");
        closeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBActionPerformed(evt);
            }
        });

        clearB.setText("Clear");
        clearB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(clearB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE)
                .addComponent(saveB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(closeB, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearB)
                    .addComponent(saveB)
                    .addComponent(closeB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jXTitledPanel1Layout = new javax.swing.GroupLayout(jXTitledPanel1.getContentContainer());
        jXTitledPanel1.getContentContainer().setLayout(jXTitledPanel1Layout);
        jXTitledPanel1Layout.setHorizontalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jXTitledPanel1Layout.setVerticalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTitledPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTitledPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        displayAddCategory();
    }//GEN-LAST:event_addBActionPerformed

    private void removeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBActionPerformed

    }//GEN-LAST:event_removeBActionPerformed

    private void closeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeBActionPerformed

    private void clearBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBActionPerformed

    }//GEN-LAST:event_clearBActionPerformed

    private void depIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depIdComboActionPerformed


    }//GEN-LAST:event_depIdComboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        displayAddepartment();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        removeDepartment();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void depNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depNameComboActionPerformed
        int index = depNameCombo.getSelectedIndex();

        if (index != depIdCombo.getSelectedIndex()) {
            ((DefaultTableModel) (categoryTable.getModel())).setRowCount(0);
            depIdCombo.setSelectedIndex(index);

            if (index > 0) {

                try {
                    handler.loadCategories(index);
                } catch (SQLException ex) {
                    Logger.getLogger(ManageDepartment.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_depNameComboActionPerformed

    private void depIdComboPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_depIdComboPopupMenuWillBecomeVisible
//        try {
//            handler.loadDepartmentCombo();
//        } catch (SQLException ex) {
//            Logger.getLogger(ManageDepartment.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_depIdComboPopupMenuWillBecomeVisible

    private void depNameComboPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_depNameComboPopupMenuWillBecomeVisible
//        try {
//            handler.loadDepartmentCombo();
//        } catch (SQLException ex) {
//            Logger.getLogger(ManageDepartment.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_depNameComboPopupMenuWillBecomeVisible

    private void depIdComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_depIdComboItemStateChanged

        int index = depIdCombo.getSelectedIndex();

        if (depNameCombo.getSelectedIndex() != index) {
            ((DefaultTableModel) (categoryTable.getModel())).setRowCount(0);

            depNameCombo.setSelectedIndex(index);

            if (index > 0) {
                try {
                    handler.loadCategories(index);
                } catch (SQLException ex) {
                    Logger.getLogger(ManageDepartment.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_depIdComboItemStateChanged

    private void catIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catIdTextActionPerformed

    private void catNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catNameTextActionPerformed

    private void CatDescTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatDescTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatDescTextActionPerformed

    private void addB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addB2ActionPerformed

        int index = depIdCombo.getSelectedIndex();
        if (index > 0) {
            try {
                if (handler.addCategory(index)) {
                    updateCategory.setVisible(false);
                }

            } catch (SQLException ex) {
                Logger.getLogger(ManageDepartment.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addB2ActionPerformed

    private void closeB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeB2ActionPerformed
        updateCategory.setVisible(false);
    }//GEN-LAST:event_closeB2ActionPerformed

    private void closeB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeB3ActionPerformed
        updateDepartment.setVisible(false);
    }//GEN-LAST:event_closeB3ActionPerformed

    private void saveDepBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDepBActionPerformed

        saveDepartmentUpdates();

    }//GEN-LAST:event_saveDepBActionPerformed

    private void depNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depNameTextActionPerformed

    private void depIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depIdTextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        displayEditDepartment();
    }//GEN-LAST:event_jButton3ActionPerformed

    public JTextField getDepIdText() {
        return depIdText;
    }

    public JTextField getDepNameText() {
        return depNameText;
    }

    public JComboBox getDepIdCombo() {
        return depIdCombo;
    }

    public JComboBox getDepNameCombo() {
        return depNameCombo;
    }

    public JTable getCategoryTable() {
        return categoryTable;
    }

    public JFrame getAddCategory() {
        return updateCategory;
    }

    public JFrame getAddDepartment() {
        return updateDepartment;
    }


    public JTextField getDescText() {
        return CatDescText;
    }

    public JTextField getIdText() {
        return catIdText;
    }

    public JTextField getNameText() {
        return catNameText;
    }

    public void setIdComment(String comment) {
        idComment.setText(comment);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDepartment.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(ManageDepartment.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new ManageDepartment().setVisible(true);

                } catch (SQLException ex) {
                    Logger.getLogger(ManageDepartment.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CatDescText;
    private javax.swing.JButton addB;
    private javax.swing.JButton addB2;
    private javax.swing.JPanel buttonPanel1;
    private javax.swing.JPanel buttonPanel2;
    private javax.swing.JTextField catIdText;
    private javax.swing.JTextField catNameText;
    private org.jdesktop.swingx.JXTitledPanel catTitlePanel;
    private javax.swing.JTable categoryTable;
    private javax.swing.JButton clearB;
    private javax.swing.JButton closeB;
    private javax.swing.JButton closeB2;
    private javax.swing.JButton closeB3;
    private javax.swing.JComboBox depIdCombo;
    private javax.swing.JTextField depIdText;
    private javax.swing.JComboBox depNameCombo;
    private javax.swing.JTextField depNameText;
    private javax.swing.JButton editB;
    private javax.swing.JPanel enterPanel1;
    private javax.swing.JPanel enterPanel2;
    private javax.swing.JPanel fullPanel1;
    private javax.swing.JLabel idComment;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JLabel idLabel2;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JLabel nameLabel4;
    private javax.swing.JButton removeB;
    private javax.swing.JButton saveB;
    private javax.swing.JButton saveDepB;
    private javax.swing.JFrame updateCategory;
    private org.jdesktop.swingx.JXTitledPanel updateDepPanel;
    private javax.swing.JFrame updateDepartment;
    // End of variables declaration//GEN-END:variables

    private void displayAddepartment() {
        
        isEditing = false;
        depIdText.setText(handler.getDepartmentNextId());
        depNameText.setText("");

        updateDepPanel.setTitle("Add Department");

        updateDepartment.setLocationRelativeTo(null);
        updateDepartment.setVisible(true);
    }

    private void displayEditDepartment() {

        if (!depIdCombo.getSelectedItem().toString().trim().equals("")) {

            isEditing = true;

            depIdText.setText(depIdCombo.getSelectedItem().toString());
            depNameText.setText(depNameCombo.getSelectedItem().toString());

            updateDepPanel.setTitle("Edit Department");

            updateDepartment.setLocationRelativeTo(null);
            updateDepartment.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Please select the department to be edited");
        }
    }

    private void saveDepartmentUpdates() {
        try {

            if (!isEditing && handler.addDepartment()) {
                updateDepartment.setVisible(false);
            } else if (isEditing && handler.updateDepartment()) {
                updateDepartment.setVisible(false);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error! Department update failed", "Unknown Error", 0);
        }
    }

    private void removeDepartment() {
        if (!depIdCombo.getSelectedItem().toString().trim().equals("")) {
            try {
                int ans = JOptionPane.showConfirmDialog(this, "Do you want to remove Department : " +depNameCombo.getSelectedItem().toString().trim() + " ?", "Remove Department", 0);
                if (ans == 0){
                    handler.removeDepartment();
                }
            } catch (SQLException ex) {
                Logger.getLogger(ManageDepartment.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select the Department to be deleted");
        }
    }

    private void displayAddCategory() {
        if (depIdCombo.getSelectedIndex() > 0) {
            
            isEditing = false;
            
            catIdText.setText(handler.getCategoryNextId());
            catNameText.setText("");

            
            catIdText.setText(handler.getCategoryNextId());
            
            catTitlePanel.setTitle("Add Category");
            updateCategory.setLocationRelativeTo(null);
            updateCategory.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Please select a Department");
        }
    }
    
    
}
