/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view.inventory;

import java.sql.SQLException;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import jxl.common.Logger;
import ui.handler.inventory.ManageDepartmentHandler;
import util.Utilities;

/**
 *
 * @author Nadheesh
 */
public class ManageDepartment extends javax.swing.JInternalFrame {

    private String idString;
    private String nameString;
    private String[] colTitle;
    private Class[] colTypes;
    private int[] colSizes;
    private int colCount;
    private String tableName;
    private ManageDepartmentHandler handler;
    private boolean isEditing;
    private final static Logger logger = Logger.getLogger(ManageDepartment.class);

    /**
     *
     * Creates new form AddDepartment
     */
    public ManageDepartment() throws SQLException {

        colCount = 6;
        idString = "Department";
        nameString = "Department";
        tableName = "Categories";
        handler = new ManageDepartmentHandler(this);
        isEditing = false;
        initComponents();

        //center data in the table
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        categoryTable.setDefaultRenderer(String.class, centerRenderer);

        categoryTable.setDragEnabled(false);

        //----------------------------------------------------------------------------------------
        handler.loadDepartmentCombo();

        //--------------------------------------------------------------------------------------
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateDepartment = new javax.swing.JDialog();
        fullPanel2 = new javax.swing.JPanel();
        updateDepPanel = new org.jdesktop.swingx.JXTitledPanel();
        enterPanel3 = new javax.swing.JPanel();
        idLabel3 = new javax.swing.JLabel();
        nameLabel5 = new javax.swing.JLabel();
        depIdText = new javax.swing.JTextField();
        depNameText = new javax.swing.JTextField();
        buttonPanel3 = new javax.swing.JPanel();
        saveDepB = new javax.swing.JButton();
        closeB3 = new javax.swing.JButton();
        updateCategory = new javax.swing.JDialog();
        catTitlePanel3 = new org.jdesktop.swingx.JXTitledPanel();
        enterPanel5 = new javax.swing.JPanel();
        idLabel5 = new javax.swing.JLabel();
        nameLabel9 = new javax.swing.JLabel();
        catIdText2 = new javax.swing.JTextField();
        catNameText2 = new javax.swing.JTextField();
        nameLabel10 = new javax.swing.JLabel();
        CatDescText2 = new javax.swing.JTextField();
        buttonPanel2 = new javax.swing.JPanel();
        addB2 = new javax.swing.JButton();
        closeB2 = new javax.swing.JButton();
        jXTitledPanel1 = new org.jdesktop.swingx.JXTitledPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        depIdCombo = new javax.swing.JComboBox();
        depNameCombo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addB = new javax.swing.JButton();
        editB = new javax.swing.JButton();
        removeB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        closeB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        updateDepartment.setMinimumSize(new java.awt.Dimension(401, 258));
        updateDepartment.setModal(true);
        updateDepartment.setResizable(false);
        updateDepartment.setType(java.awt.Window.Type.POPUP);

        fullPanel2.setPreferredSize(new java.awt.Dimension(775, 319));

        updateDepPanel.setTitle("Add Department");
        updateDepPanel.setTitleFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        enterPanel3.setBorder(dropShadowBorder1);

        idLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idLabel3.setText("Department ID");

        nameLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLabel5.setText("Department Name");

        depIdText.setEditable(false);
        depIdText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        depIdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depIdTextActionPerformed(evt);
            }
        });

        depNameText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        depNameText.setText("  ");
        depNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depNameTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enterPanel3Layout = new javax.swing.GroupLayout(enterPanel3);
        enterPanel3.setLayout(enterPanel3Layout);
        enterPanel3Layout.setHorizontalGroup(
            enterPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterPanel3Layout.createSequentialGroup()
                        .addComponent(idLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(depIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterPanel3Layout.createSequentialGroup()
                        .addComponent(nameLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        enterPanel3Layout.setVerticalGroup(
            enterPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(enterPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        saveDepB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveDepB.setText("Save");
        saveDepB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveDepBActionPerformed(evt);
            }
        });

        closeB3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        closeB3.setText("Cancel");
        closeB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeB3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanel3Layout = new javax.swing.GroupLayout(buttonPanel3);
        buttonPanel3.setLayout(buttonPanel3Layout);
        buttonPanel3Layout.setHorizontalGroup(
            buttonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(saveDepB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeB3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        buttonPanel3Layout.setVerticalGroup(
            buttonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(buttonPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveDepB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeB3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout updateDepPanelLayout = new javax.swing.GroupLayout(updateDepPanel.getContentContainer());
        updateDepPanel.getContentContainer().setLayout(updateDepPanelLayout);
        updateDepPanelLayout.setHorizontalGroup(
            updateDepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateDepPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateDepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enterPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        updateDepPanelLayout.setVerticalGroup(
            updateDepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateDepPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fullPanel2Layout = new javax.swing.GroupLayout(fullPanel2);
        fullPanel2.setLayout(fullPanel2Layout);
        fullPanel2Layout.setHorizontalGroup(
            fullPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateDepPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fullPanel2Layout.setVerticalGroup(
            fullPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateDepPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout updateDepartmentLayout = new javax.swing.GroupLayout(updateDepartment.getContentPane());
        updateDepartment.getContentPane().setLayout(updateDepartmentLayout);
        updateDepartmentLayout.setHorizontalGroup(
            updateDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        updateDepartmentLayout.setVerticalGroup(
            updateDepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fullPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
        );

        updateCategory.setMinimumSize(new java.awt.Dimension(534, 260));
        updateCategory.setModal(true);
        updateCategory.setResizable(false);

        catTitlePanel3.setTitle("Add Category");
        catTitlePanel3.setTitleFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        catTitlePanel3.setMinimumSize(new java.awt.Dimension(367, 183));

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        enterPanel5.setBorder(dropShadowBorder2);

        idLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idLabel5.setText("Category ID");

        nameLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLabel9.setText("Category Name");

        catIdText2.setEditable(false);
        catIdText2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        catIdText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catIdText2catIdTextActionPerformed(evt);
            }
        });

        catNameText2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        catNameText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catNameText2catNameTextActionPerformed(evt);
            }
        });

        nameLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameLabel10.setText("Description");

        CatDescText2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CatDescText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatDescText2CatDescTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout enterPanel5Layout = new javax.swing.GroupLayout(enterPanel5);
        enterPanel5.setLayout(enterPanel5Layout);
        enterPanel5Layout.setHorizontalGroup(
            enterPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enterPanel5Layout.createSequentialGroup()
                        .addComponent(nameLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CatDescText2))
                    .addGroup(enterPanel5Layout.createSequentialGroup()
                        .addGroup(enterPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(enterPanel5Layout.createSequentialGroup()
                                .addComponent(nameLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(catNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(idLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(enterPanel5Layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(catIdText2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 183, Short.MAX_VALUE)))
                .addContainerGap())
        );
        enterPanel5Layout.setVerticalGroup(
            enterPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(enterPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(catIdText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(enterPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catNameText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(enterPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CatDescText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        addB2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addB2.setText("Save");
        addB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addB2ActionPerformed(evt);
            }
        });

        closeB2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        closeB2.setText("Cancel");
        closeB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeB2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanel2Layout = new javax.swing.GroupLayout(buttonPanel2);
        buttonPanel2.setLayout(buttonPanel2Layout);
        buttonPanel2Layout.setHorizontalGroup(
            buttonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addB2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeB2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        buttonPanel2Layout.setVerticalGroup(
            buttonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(buttonPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addB2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeB2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout catTitlePanel3Layout = new javax.swing.GroupLayout(catTitlePanel3.getContentContainer());
        catTitlePanel3.getContentContainer().setLayout(catTitlePanel3Layout);
        catTitlePanel3Layout.setHorizontalGroup(
            catTitlePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catTitlePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(catTitlePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        catTitlePanel3Layout.setVerticalGroup(
            catTitlePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catTitlePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout updateCategoryLayout = new javax.swing.GroupLayout(updateCategory.getContentPane());
        updateCategory.getContentPane().setLayout(updateCategoryLayout);
        updateCategoryLayout.setHorizontalGroup(
            updateCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catTitlePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        updateCategoryLayout.setVerticalGroup(
            updateCategoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(catTitlePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/view/system/resources/coop_200.png"))); // NOI18N

        jXTitledPanel1.setTitle("");
        jXTitledPanel1.setTitleFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jXTitledPanel1.setTitlePainter(null);

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        jPanel1.setBorder(dropShadowBorder3);
        jPanel1.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText(idString+ " "+ "ID");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText(nameString+ " "+ "Name");

        jLabel3.setText("  ");

        depIdCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        depIdCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        depIdCombo.setAutoscrolls(true);
        depIdCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                depIdComboItemStateChanged(evt);
            }
        });
        depIdCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                depIdComboPopupMenuWillBecomeVisible(evt);
            }
        });
        depIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depIdComboActionPerformed(evt);
            }
        });

        depNameCombo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        depNameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        depNameCombo.setAutoscrolls(true);
        depNameCombo.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                depNameComboPopupMenuWillBecomeVisible(evt);
            }
        });
        depNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depNameComboActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("New Entry");
        jButton2.setMaximumSize(new java.awt.Dimension(120, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(120, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(120, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Edit Department");
        jButton3.setMaximumSize(new java.awt.Dimension(120, 30));
        jButton3.setMinimumSize(new java.awt.Dimension(120, 30));
        jButton3.setPreferredSize(new java.awt.Dimension(120, 30));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Remove");
        jButton4.setMaximumSize(new java.awt.Dimension(120, 30));
        jButton4.setMinimumSize(new java.awt.Dimension(120, 30));
        jButton4.setPreferredSize(new java.awt.Dimension(120, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depIdCombo, 0, 244, Short.MAX_VALUE)
                    .addComponent(depNameCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(depIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(depNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Update "+ tableName, javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));

        addB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addB.setText("New Entry");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        editB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        editB.setText("Edit Category");
        editB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBActionPerformed(evt);
            }
        });

        removeB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        removeB.setText("Remove");
        removeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(addB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeB, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder4 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder4.setShowLeftShadow(true);
        dropShadowBorder4.setShowTopShadow(true);
        jScrollPane1.setBorder(dropShadowBorder4);

        categoryTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        categoryTable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cateogory ID", "Category Name", "Description", "Discount (%)", "Discount Start Date", "Discount Finish Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        categoryTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        categoryTable.setColumnSelectionAllowed(true);
        categoryTable.setFillsViewportHeight(true);
        categoryTable.setFocusCycleRoot(true);
        categoryTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(categoryTable);
        categoryTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (categoryTable.getColumnModel().getColumnCount() > 0) {
            categoryTable.getColumnModel().getColumn(0).setMinWidth(100);
            categoryTable.getColumnModel().getColumn(0).setPreferredWidth(100);
            categoryTable.getColumnModel().getColumn(1).setMinWidth(150);
            categoryTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            categoryTable.getColumnModel().getColumn(2).setMinWidth(200);
            categoryTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            categoryTable.getColumnModel().getColumn(3).setMinWidth(100);
            categoryTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            categoryTable.getColumnModel().getColumn(4).setMinWidth(125);
            categoryTable.getColumnModel().getColumn(4).setPreferredWidth(125);
            categoryTable.getColumnModel().getColumn(5).setMinWidth(130);
            categoryTable.getColumnModel().getColumn(5).setPreferredWidth(130);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        closeB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        closeB.setText("OK");
        closeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(682, Short.MAX_VALUE)
                .addComponent(closeB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(closeB, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel4.setBackground(java.awt.SystemColor.activeCaptionBorder);
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Manage Departments");
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout jXTitledPanel1Layout = new javax.swing.GroupLayout(jXTitledPanel1.getContentContainer());
        jXTitledPanel1.getContentContainer().setLayout(jXTitledPanel1Layout);
        jXTitledPanel1Layout.setHorizontalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jXTitledPanel1Layout.setVerticalGroup(
            jXTitledPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTitledPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTitledPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTitledPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        displayAddCategory();
    }//GEN-LAST:event_addBActionPerformed

    private void removeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBActionPerformed
        removeCategory();
    }//GEN-LAST:event_removeBActionPerformed

    private void closeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_closeBActionPerformed

    private void depIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depIdComboActionPerformed


    }//GEN-LAST:event_depIdComboActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        displayAddepartment();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        removeDepartment();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void depNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depNameComboActionPerformed
        int index = depNameCombo.getSelectedIndex();

        if (index != depIdCombo.getSelectedIndex()) {
            ((DefaultTableModel) (categoryTable.getModel())).setRowCount(0);
            depIdCombo.setSelectedIndex(index);

            if (index > 0) {

                try {
                    handler.loadCategories(index);
                } catch (SQLException ex) {
                    logger.error(ex);
                }
            }
        }
    }//GEN-LAST:event_depNameComboActionPerformed

    private void depIdComboPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_depIdComboPopupMenuWillBecomeVisible
//        try {
//            handler.loadDepartmentCombo();
//        } catch (SQLException ex) {
//            Logger.getLogger(ManageDepartment.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_depIdComboPopupMenuWillBecomeVisible

    private void depNameComboPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_depNameComboPopupMenuWillBecomeVisible
//        try {
//            handler.loadDepartmentCombo();
//        } catch (SQLException ex) {
//            Logger.getLogger(ManageDepartment.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_depNameComboPopupMenuWillBecomeVisible

    private void depIdComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_depIdComboItemStateChanged

        int index = depIdCombo.getSelectedIndex();

        if (depNameCombo.getSelectedIndex() != index) {
            ((DefaultTableModel) (categoryTable.getModel())).setRowCount(0);

            depNameCombo.setSelectedIndex(index);

            if (index > 0) {
                try {
                    handler.loadCategories(index);
                } catch (SQLException ex) {
                    logger.error(ex);
                }
            }
        }
    }//GEN-LAST:event_depIdComboItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        displayEditDepartment();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void depIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depIdTextActionPerformed

    private void depNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depNameTextActionPerformed

    private void saveDepBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveDepBActionPerformed
        saveDepartmentUpdates();
    }//GEN-LAST:event_saveDepBActionPerformed

    private void closeB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeB3ActionPerformed
        updateDepartment.setVisible(false);
    }//GEN-LAST:event_closeB3ActionPerformed

    private void catIdText2catIdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catIdText2catIdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catIdText2catIdTextActionPerformed

    private void catNameText2catNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catNameText2catNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catNameText2catNameTextActionPerformed

    private void CatDescText2CatDescTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatDescText2CatDescTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatDescText2CatDescTextActionPerformed

    private void addB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addB2ActionPerformed
        int index = depIdCombo.getSelectedIndex();
        if (index > 0) {
            try {
                if (!isEditing && handler.addCategory(index)) {
                    updateCategory.setVisible(false);
                } else if (isEditing && handler.editCategory(index)) {
                    updateCategory.setVisible(false);
                }
            } catch (SQLException ex) {
                Utilities.ShowErrorMsg(this, "Upadating failed! Database Error");
            }
        } else {
            Utilities.ShowErrorMsg(this, "Please select a department");
        }
    }//GEN-LAST:event_addB2ActionPerformed

    private void closeB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeB2ActionPerformed
        updateCategory.setVisible(false);
    }//GEN-LAST:event_closeB2ActionPerformed

    private void editBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBActionPerformed
        displayUpdadateCategory();
    }//GEN-LAST:event_editBActionPerformed

    public JTextField getDepIdText() {
        return depIdText;
    }

    public JTextField getDepNameText() {
        return depNameText;
    }

    public JComboBox getDepIdCombo() {
        return depIdCombo;
    }

    public JComboBox getDepNameCombo() {
        return depNameCombo;
    }

    public JTable getCategoryTable() {
        return categoryTable;
    }

    public JTextField getDescText() {
        return CatDescText2;
    }

    public JTextField getIdText() {
        return catIdText2;
    }

    public JTextField getNameText() {
        return catNameText2;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDepartment.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            logger.error(ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new ManageDepartment().setVisible(true);

                } catch (SQLException ex) {
                    logger.error(ex);
                }
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CatDescText2;
    private javax.swing.JButton addB;
    private javax.swing.JButton addB2;
    private javax.swing.JPanel buttonPanel2;
    private javax.swing.JPanel buttonPanel3;
    private javax.swing.JTextField catIdText2;
    private javax.swing.JTextField catNameText2;
    private org.jdesktop.swingx.JXTitledPanel catTitlePanel3;
    private javax.swing.JTable categoryTable;
    private javax.swing.JButton closeB;
    private javax.swing.JButton closeB2;
    private javax.swing.JButton closeB3;
    private javax.swing.JComboBox depIdCombo;
    private javax.swing.JTextField depIdText;
    private javax.swing.JComboBox depNameCombo;
    private javax.swing.JTextField depNameText;
    private javax.swing.JButton editB;
    private javax.swing.JPanel enterPanel3;
    private javax.swing.JPanel enterPanel5;
    private javax.swing.JPanel fullPanel2;
    private javax.swing.JLabel idLabel3;
    private javax.swing.JLabel idLabel5;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXTitledPanel jXTitledPanel1;
    private javax.swing.JLabel nameLabel10;
    private javax.swing.JLabel nameLabel5;
    private javax.swing.JLabel nameLabel9;
    private javax.swing.JButton removeB;
    private javax.swing.JButton saveDepB;
    private javax.swing.JDialog updateCategory;
    private org.jdesktop.swingx.JXTitledPanel updateDepPanel;
    private javax.swing.JDialog updateDepartment;
    // End of variables declaration//GEN-END:variables

    private void displayAddepartment() {

        isEditing = false;
        depIdText.setText(handler.getDepartmentNextId());
        depNameText.setText("");

        updateDepPanel.setTitle("Add Department");

        updateDepartment.setLocationRelativeTo(null);
        updateDepartment.setVisible(true);
    }

    private void displayEditDepartment() {

        if (!depIdCombo.getSelectedItem().toString().trim().equals("")) {

            isEditing = true;

            depIdText.setText(depIdCombo.getSelectedItem().toString());
            depNameText.setText(depNameCombo.getSelectedItem().toString());

            updateDepPanel.setTitle("Edit Department");

            updateDepartment.setLocationRelativeTo(null);
            updateDepartment.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Please select the department to be edited");
        }
    }

    private void saveDepartmentUpdates() {
        try {

            if (!isEditing && handler.addDepartment()) {
                updateDepartment.setVisible(false);
            } else if (isEditing && handler.updateDepartment()) {
                updateDepartment.setVisible(false);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error! Department update failed", "Unknown Error", 0);
        }
    }

    private void removeDepartment() {
        if (!depIdCombo.getSelectedItem().toString().trim().equals("")) {
            try {
                int ans = JOptionPane.showConfirmDialog(this, "Do you want to remove Department : " + depNameCombo.getSelectedItem().toString().trim() + " ?", "Remove Department", 0);
                if (ans == 0) {
                    handler.removeDepartment();
                }
            } catch (SQLException ex) {
                logger.error(ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select the Department to be deleted");
        }
    }

    private void displayAddCategory() {
        if (depIdCombo.getSelectedIndex() > 0) {

            isEditing = false;

            catIdText2.setText(handler.getCategoryNextId());
            catNameText2.setText("");
            CatDescText2.setText("");

            catTitlePanel3.setTitle("Add Category");
            updateCategory.setLocationRelativeTo(null);
            updateCategory.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a Department");
        }
    }

    private void displayUpdadateCategory() {

        if (depIdCombo.getSelectedIndex() > 0) {

            int selRow = categoryTable.getSelectedRow();

            if (selRow >= 0) {
                isEditing = true;

                if (categoryTable.getValueAt(selRow, 0) != null) {
                    catIdText2.setText(categoryTable.getValueAt(selRow, 0).toString());
                } else {
                    catIdText2.setText("");
                }
                if (categoryTable.getValueAt(selRow, 1) != null) {
                    catNameText2.setText(categoryTable.getValueAt(selRow, 1).toString());
                } else {
                    catNameText2.setText("");
                }
                if (categoryTable.getValueAt(selRow, 2) != null) {
                    CatDescText2.setText(categoryTable.getValueAt(selRow, 2).toString());
                } else {
                    CatDescText2.setText("");
                }

                catTitlePanel3.setTitle("Edit Category");
                updateCategory.setLocationRelativeTo(null);
                updateCategory.setVisible(true);

            } else {
                JOptionPane.showMessageDialog(this, "Please select a Category to be Edited");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a Department");
        }
    }

    private void removeCategory() {
        if (depIdCombo.getSelectedIndex() > 0) {

            int selRow = categoryTable.getSelectedRow();

            if (selRow >= 0) {

                try {
                    int ans = JOptionPane.showConfirmDialog(this, "Do you want to remove Category : " + categoryTable.getValueAt(selRow, 1) + " ?", "Remove Category", 0);
                    if (ans == 0) {
                        handler.removeCategory();
                    }
                } catch (SQLException ex) {
                    logger.error(ex);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Please select a Category to be Removed");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a Department");
        }
    }

    public void setVisible(boolean isVisible) {
        super.setVisible(isVisible);
        try {
            if (handler != null) {
                handler.loadDepartmentCombo();
            }
        } catch (SQLException ex) {
            logger.error(ex);
        }
    }
}
