package ui.view.ledger;
//
// <editor-fold defaultstate="collapsed" desc="Imports">

import controller.inventory.ProductController;
import controller.ledger.DamagedStockController;
import controller.ledger.SupplierReturnNoteController;
import database.connector.DBConnection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import model.inventory.Batch;
import model.inventory.Product;
import model.ledger.DamageStock;
import model.ledger.SupplierReturnNote;
import model.ledger.item.DamagedItem;
import model.ledger.item.DamagedItemBuilder;
import model.ledger.item.SRNItem;
import model.ledger.item.SRNItemBuilder;
import model.supplier.Supplier;

// </editor-fold>
// 
public class DamageStockInterface extends javax.swing.JInternalFrame implements BatchSelectorInterface {
    //
    // <editor-fold defaultstate="collapsed" desc="Variables">

    private static final org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(DamageStockInterface.class);

    private final DefaultTableModel model;

    // </editor-fold>
    //
    // <editor-fold defaultstate="collapsed" desc="Netbeans generated">
    /**
     * Creates new form GRNInterface
     */
    public DamageStockInterface() {
        initComponents();
        initInterface();
        model = (DefaultTableModel) itemDataTable.getModel();
        model.addTableModelListener(new TableModelListenerImpl(model, txtTotal));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtf17Number = new javax.swing.JTextField();
        comboLocation = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemDataTable = new javax.swing.JTable();
        btnNewItem = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();
        btnAddDamagedStock = new javax.swing.JButton();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        lblTitle = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("F17 Number");

        jLabel2.setText("Date");

        jLabel6.setText("Location");

        txtf17Number.setEditable(false);

        itemDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Item Code", "Description", "Damaged Quantity", "Unit Price", "Quantity", "Value", "Loss"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemDataTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        itemDataTable.setColumnSelectionAllowed(true);
        itemDataTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        itemDataTable.setRowHeight(30);
        itemDataTable.getTableHeader().setReorderingAllowed(false);
        itemDataTable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                itemDataTableInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(itemDataTable);
        itemDataTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (itemDataTable.getColumnModel().getColumnCount() > 0) {
            itemDataTable.getColumnModel().getColumn(0).setResizable(false);
            itemDataTable.getColumnModel().getColumn(0).setPreferredWidth(20);
            itemDataTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            itemDataTable.getColumnModel().getColumn(2).setPreferredWidth(400);
            itemDataTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            itemDataTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            itemDataTable.getColumnModel().getColumn(5).setPreferredWidth(100);
            itemDataTable.getColumnModel().getColumn(6).setPreferredWidth(100);
            itemDataTable.getColumnModel().getColumn(7).setPreferredWidth(100);
        }

        btnNewItem.setText("Add");
        btnNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewItemActionPerformed(evt);
            }
        });

        btnDeleteItem.setText("Delete");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        btnAddDamagedStock.setText("Finish");
        btnAddDamagedStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDamagedStockActionPerformed(evt);
            }
        });

        lblTitle.setBackground(java.awt.SystemColor.textHighlight);
        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setLabelFor(this);
        lblTitle.setText("Damage Stock");
        lblTitle.setAlignmentY(0.0F);
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblTitle.setName(""); // NOI18N
        lblTitle.setOpaque(true);

        txtTotal.setEditable(false);

        jLabel3.setText("Total");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datePicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtf17Number, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddDamagedStock, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtf17Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDamagedStock)
                    .addComponent(btnDeleteItem)
                    .addComponent(btnNewItem)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewItemActionPerformed
        addItem();
    }//GEN-LAST:event_btnNewItemActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        deleteItem();
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void itemDataTableInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_itemDataTableInputMethodTextChanged

    }//GEN-LAST:event_itemDataTableInputMethodTextChanged

    private void btnAddDamagedStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDamagedStockActionPerformed
        recordDamagedGoods();
    }//GEN-LAST:event_btnAddDamagedStockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DamageStockInterface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DamageStockInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDamagedStock;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnNewItem;
    private javax.swing.JComboBox comboLocation;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JTable itemDataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtf17Number;
    // End of variables declaration//GEN-END:variables
        // </editor-fold>
    //
    // <editor-fold defaultstate="collapsed" desc="Interface Management">

    private void initInterface() {
        // Add stores here
        comboLocation.addItem("stores");

        try {
            txtf17Number.setText(DamagedStockController.getNextDamagedStockID());
        } catch (SQLException ex) {
            logger.error("Error: " + ex.getMessage());
            util.Utilities.showMsgBox("Error: Cannot connect to database!", "Database Connection Error", 0);
            this.dispose();
        }

        datePicker.setDate(util.Utilities.getToday());
    }

    // </editor-fold>
    //
    // <editor-fold defaultstate="collapsed" desc="Item Management">
    private void addItem() {
        BatchSelectionDialog d = new BatchSelectionDialog(this);
        ((JDesktopPane) this.getParent()).add(d);
        d.centerOnDesktop();
        d.setVisible(true);
        /*
         if (model.getRowCount() == 0 || isItemValid(model.getRowCount() - 1)) {
         model.addRow(new Object[]{model.getRowCount() + 1, "", "", "", "", "", ""});
         }*/
    }

    private boolean isItemValid(int row) {
        if (row >= 0 && row < model.getRowCount()) {
            for (int i = 0; i < model.getColumnCount(); i++) {
                if (model.getValueAt(row, i) == "" && model.isCellEditable(row, i)) {
                    return false;
                }
            }
            return true;
        }
        return false;
    }

    private void deleteItem() {
        if (itemDataTable.getSelectedRow() >= 0 && itemDataTable.getSelectedRow() < model.getRowCount()) {
            model.removeRow(itemDataTable.getSelectedRow());
            for (int i = 0; i < model.getRowCount(); i++) {
                model.setValueAt(i + 1, i, 0);
            }
        }
    }

    @Override
    public void batchSelectionResponce(Batch b) {
        if (model.getRowCount() == 0 || isItemValid(model.getRowCount() - 1)) {
            try {
                model.addRow(new Object[]{
                    model.getRowCount() + 1,
                    b,
                    ProductController.getProduct(b.getProductId()),
                    "0",
                    b.getUnit_price(),
                    b.getRecievedQuantity() - b.getSoldQty(),
                    "0",
                    "0"});
            } catch (SQLException ex) {
                logger.error(ex.getMessage());
            }
        }
    }

    private static class TableModelListenerImpl implements TableModelListener {

        private void fillProductDetails(int row, String productId) {
            Product result;
            try {
                result = ProductController.getProduct(productId);
                model.setValueAt(result.getProductName(), row, 2);
            } catch (SQLException ex) {
                logger.error(ex.getMessage());
                model.setValueAt("", row, 2);
            } finally {
                try {
                    DBConnection.closeConnectionToDB();
                } catch (SQLException ex) {
                    logger.error(ex.getMessage());
                }
            }
        }

        private final DefaultTableModel model;

        private final JTextField textBox;

        public TableModelListenerImpl(DefaultTableModel model, JTextField textBox) {
            this.model = model;
            this.textBox = textBox;
        }

        @Override
        public void tableChanged(TableModelEvent e) {
            this.model.removeTableModelListener(this);
            Double totalLoss = 0.0;
            for (int row = 0; row < model.getRowCount(); row++) {
                try {
                    if (e.getColumn() != 2 && e.getColumn() != 7 && e.getColumn() != 6) {

                        // Auto generated Column
                        String productId = model.getValueAt(row, 1).toString();
                        fillProductDetails(row, productId);

                        // Auto generated Column
                        Double damagedQuantity;
                        Double stockQuantity;
                        try {
                            damagedQuantity = Double.parseDouble(model.getValueAt(row, 3).toString());
                            stockQuantity = Double.parseDouble(model.getValueAt(row, 5).toString());

                            if (damagedQuantity >= 0 && damagedQuantity > stockQuantity) {
                                model.setValueAt(model.getValueAt(row, 8).toString(), row, 3);
                            } else if (damagedQuantity < 0) {
                                model.setValueAt("0", row, 3);
                            }

                        } catch (Exception ex) {
                            model.setValueAt("0", row, 3);
                        }

                        damagedQuantity = Double.parseDouble(model.getValueAt(row, 3).toString());
                        stockQuantity = Double.parseDouble(model.getValueAt(row, 5).toString());

                        Double result = stockQuantity
                                * Double.parseDouble(model.getValueAt(row, 5).toString());
                        model.setValueAt(result.toString(), row, 6);

                        result = damagedQuantity
                                * Double.parseDouble(model.getValueAt(row, 4).toString());
                        model.setValueAt(result.toString(), row, 7);
                        totalLoss += result;
                    }
                    textBox.setText(totalLoss.toString());
                    // model.fireTableCellUpdated(row, 8);\;
                } catch (Exception ex) {
                    logger.error("Failed to fill data: " + ex.getMessage());
                }
                // for (int column = 0; column < model.getColumnCount(); column++) {}
            }
            this.model.addTableModelListener(this);
        }
    }

    // </editor-fold>
    //    
    // <editor-fold defaultstate="collapsed" desc="Damaged Goods Managament">
    private void recordDamagedGoods() {

        DamageStock damagedGood = new DamageStock(
                txtf17Number.getText(),
                datePicker.getDate(),
                (String) comboLocation.getSelectedItem()
        );

        for (int i = 0; i < model.getRowCount(); i++) {
            DamagedItem itm;
            try {
                itm = new DamagedItemBuilder()
                        .setBatchID(((Batch) model.getValueAt(i, 1)).getBatchId())
                        .setQuantity(Double.parseDouble(model.getValueAt(i, 5).toString()))
                        .setDamagedItemID(txtf17Number.getText())
                        .setQuantityDamaged(Double.parseDouble(model.getValueAt(i, 3).toString()))
                        .setSellingPrice(Double.parseDouble(model.getValueAt(i, 4).toString()))
                        .createDamagedItem();
                damagedGood.addItem(itm);
            } catch (Exception ex) {
                util.Utilities.showMsgBox("Unable to add Damaged Good item, Invalid item",
                        "Damaged Good Error",
                        0);
                return;
            }
        }
        try {
            DamagedStockController.addDamagedStock(damagedGood);
            util.Utilities.showMsgBox("Damaged Good added successfully",
                    "Damaged Good record Success",
                    1);

            this.dispose();
        } catch (SQLException ex) {
            util.Utilities.showMsgBox("Unable to add Dmaged goods to database",
                    "Damaged Good record Error",
                    0);

            logger.error(ex.getMessage());
        }
    }
    // </editor-fold>
}
