package ui.view.ledger;
//
//
// <editor-fold defaultstate="collapsed" desc="Imports">

import com.sun.corba.se.spi.logging.CORBALogDomains;
import controller.inventory.BatchController;
import controller.inventory.ProductController;
import controller.ledger.GoodRecieveNoteController;
import controller.supplier.SupplierController;
import database.connector.DBConnection;
import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.PlainDocument;
import model.inventory.Batch;
import model.inventory.BatchBuilder;
import model.inventory.Product;
import model.ledger.GoodRecieveNote;
import model.supplier.Supplier;
import util.CurrencyFilter;
import util.DoubleFilter;

// </editor-fold>
// 
//
public class GRNInterface extends javax.swing.JInternalFrame {
    //
    //
    // <editor-fold defaultstate="collapsed" desc="Variables">

    private static final org.apache.log4j.Logger logger = org.apache.log4j.Logger.getLogger(GRNInterface.class);

    private final DefaultTableModel model;

    // </editor-fold>
    //
    //
    // <editor-fold defaultstate="collapsed" desc="Netbeans generated">
    public GRNInterface() {
        initComponents();
        initInterface();
        model = (DefaultTableModel) itemDataTable.getModel();
        model.addTableModelListener(new TableModelListenerImpl(model));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNewItem = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();
        btnAddGrn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemDataTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtLoadingFee = new javax.swing.JTextField();
        txtSellingBillDiscount = new javax.swing.JTextField();
        txtPurchasingBillDiscount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        comboLocation = new javax.swing.JComboBox();
        comboPaymentType = new javax.swing.JComboBox();
        comboSupplier = new javax.swing.JComboBox();
        datePickInvoiceDate = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtInvoiceNo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtF16aNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitle.setBackground(java.awt.SystemColor.textHighlight);
        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setLabelFor(this);
        lblTitle.setText("Good Recieve Note (GRN)");
        lblTitle.setAlignmentY(0.0F);
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        lblTitle.setName(""); // NOI18N
        lblTitle.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnNewItem.setText("Add");
        btnNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewItemActionPerformed(evt);
            }
        });

        btnDeleteItem.setText("Delete");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        btnAddGrn.setText("Add GRN");
        btnAddGrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGrnActionPerformed(evt);
            }
        });

        itemDataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Item Code", "Description", "Cost Price", "Cost Discount", "Expiration date", "Selling Price", "Quantity", "Recieved Quantity", "Cost Value", "Selling Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true, true, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemDataTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        itemDataTable.setColumnSelectionAllowed(true);
        itemDataTable.setRowHeight(30);
        itemDataTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(itemDataTable);
        itemDataTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (itemDataTable.getColumnModel().getColumnCount() > 0) {
            itemDataTable.getColumnModel().getColumn(0).setMinWidth(30);
            itemDataTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            itemDataTable.getColumnModel().getColumn(0).setMaxWidth(30);
            itemDataTable.getColumnModel().getColumn(1).setMinWidth(100);
            itemDataTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            itemDataTable.getColumnModel().getColumn(1).setMaxWidth(100);
            itemDataTable.getColumnModel().getColumn(2).setMinWidth(200);
            itemDataTable.getColumnModel().getColumn(2).setPreferredWidth(200);
            itemDataTable.getColumnModel().getColumn(2).setMaxWidth(200);
            itemDataTable.getColumnModel().getColumn(3).setMinWidth(100);
            itemDataTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            itemDataTable.getColumnModel().getColumn(3).setMaxWidth(100);
            itemDataTable.getColumnModel().getColumn(4).setMinWidth(100);
            itemDataTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            itemDataTable.getColumnModel().getColumn(4).setMaxWidth(100);
            itemDataTable.getColumnModel().getColumn(5).setPreferredWidth(100);
            itemDataTable.getColumnModel().getColumn(6).setMinWidth(100);
            itemDataTable.getColumnModel().getColumn(6).setPreferredWidth(100);
            itemDataTable.getColumnModel().getColumn(6).setMaxWidth(100);
            itemDataTable.getColumnModel().getColumn(7).setMinWidth(100);
            itemDataTable.getColumnModel().getColumn(7).setPreferredWidth(100);
            itemDataTable.getColumnModel().getColumn(7).setMaxWidth(100);
            itemDataTable.getColumnModel().getColumn(8).setMinWidth(100);
            itemDataTable.getColumnModel().getColumn(8).setPreferredWidth(100);
            itemDataTable.getColumnModel().getColumn(8).setMaxWidth(100);
            itemDataTable.getColumnModel().getColumn(9).setPreferredWidth(100);
            itemDataTable.getColumnModel().getColumn(10).setPreferredWidth(100);
        }

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtLoadingFee.setText("0");
        txtLoadingFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoadingFeeActionPerformed(evt);
            }
        });

        txtSellingBillDiscount.setText("0");

        txtPurchasingBillDiscount.setText("0");

        jLabel9.setText("Selling");

        jLabel10.setText("Loading Fee");

        jLabel11.setText("Bill Discount");

        jLabel14.setText("Purchasing");

        comboPaymentType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPaymentTypeActionPerformed(evt);
            }
        });

        jLabel2.setText("Date");

        jLabel3.setText("Supplier");

        jLabel6.setText("Location");

        jLabel7.setText("Payment Method");

        jLabel8.setText("Invoice Code");

        txtF16aNumber.setEditable(false);

        jLabel1.setText("F16A Number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addGap(10, 10, 10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(datePickInvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtF16aNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel10)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPurchasingBillDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoadingFee, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSellingBillDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGap(16, 16, 16))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboLocation, comboPaymentType, comboSupplier, datePickInvoiceDate, txtF16aNumber, txtInvoiceNo});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtLoadingFee, txtPurchasingBillDiscount, txtSellingBillDiscount});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtF16aNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(datePickInvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(comboSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel7))
                    .addComponent(comboPaymentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtInvoiceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel9))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLoadingFee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPurchasingBillDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSellingBillDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNewItem, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddGrn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddGrn)
                    .addComponent(btnNewItem)
                    .addComponent(btnDeleteItem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        deleteItem();
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void btnNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewItemActionPerformed
        addNewItem();
    }//GEN-LAST:event_btnNewItemActionPerformed

    private void btnAddGrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGrnActionPerformed
        recordGoodRecieveNote();
    }//GEN-LAST:event_btnAddGrnActionPerformed

    private void comboPaymentTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPaymentTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboPaymentTypeActionPerformed

    private void txtLoadingFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoadingFeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoadingFeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GRNInterface.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new GRNInterface().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGrn;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnNewItem;
    private javax.swing.JComboBox comboLocation;
    private javax.swing.JComboBox comboPaymentType;
    private javax.swing.JComboBox comboSupplier;
    private org.jdesktop.swingx.JXDatePicker datePickInvoiceDate;
    private javax.swing.JTable itemDataTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtF16aNumber;
    private javax.swing.JTextField txtInvoiceNo;
    private javax.swing.JTextField txtLoadingFee;
    private javax.swing.JTextField txtPurchasingBillDiscount;
    private javax.swing.JTextField txtSellingBillDiscount;
    // End of variables declaration//GEN-END:variables

    // </editor-fold>
    //
    //
    // <editor-fold defaultstate="collapsed" desc="GRN Management">
    private void recordGoodRecieveNote() {
        GoodRecieveNote grn = new GoodRecieveNote(
                txtF16aNumber.getText(),
                txtInvoiceNo.getText(),
                datePickInvoiceDate.getDate(),
                (Supplier) comboSupplier.getSelectedItem(),
                (String) comboLocation.getSelectedItem(),
                (String) comboPaymentType.getSelectedItem(),
                Double.parseDouble(txtLoadingFee.getText()),
                Double.parseDouble(txtPurchasingBillDiscount.getText()),
                Double.parseDouble(txtSellingBillDiscount.getText())
        );

        if (grn.getSupplier() == null) {
            util.Utilities.showMsgBox("Unable to add grn, Select a valid supplier.", "Grn Error", 0);
            return;
        }

        if ("".equals(grn.getInvoiceNo())) {
            util.Utilities.showMsgBox("Unable to add grn, enter Invoice number(Code).", "Grn Error", 0);
            return;
        }
        
        if (model.getRowCount() <= 0) {
            int i = util.Utilities.showButtonMsg("This GRN dosen't contailn any items. Do you still want to add the GRN?",
                    "Alart!", JOptionPane.YES_NO_OPTION);
            if (i == 1) {
                return;
            }
        }

        for (int i = 0; i < model.getRowCount(); i++) {
            try {
                if (!GRNInterface.isItemValid(i, model)) {
                    util.Utilities.showMsgBox("Unable to add grn, Invalid batch", "Grn Error", 0);
                    return;
                }

                Date date = util.Utilities.getDateFromString(model.getValueAt(i, 5).toString());
                if (date == null) {
                    util.Utilities.showMsgBox("Unable to add grn, Invalid batch", "Grn Error", 0);
                    return;
                }
                Batch b
                        = (BatchBuilder.Batch())
                        .withBatchId(BatchController.getNextBatchID())
                        .withGRNNumber(txtF16aNumber.getText())
                        .withProductId("P" + model.getValueAt(i, 1).toString())
                        .withUnitCost(Double.parseDouble(model.getValueAt(i, 3).toString()))
                        .withCostDiscount(Double.parseDouble(model.getValueAt(i, 4).toString()))
                        .withUnitPrice(Double.parseDouble(model.getValueAt(i, 6).toString()))
                        .withQuantity(Double.parseDouble(model.getValueAt(i, 7).toString()))
                        .withExpirationDate(date)
                        .withNotificationDate(null)
                        .withRecievedQuantity(Double.parseDouble(model.getValueAt(i, 8).toString()))
                        .withSoldQty(0.0)
                        .withDiscounted(false)
                        .withInStock(true)
                        .build();
                grn.addBatch(b);
            } catch (Exception ex) {
                util.Utilities.showMsgBox("Unable to add grn, Invalid batch", "Grn Error", 0);
                return;
            }
        }

        try {
            GoodRecieveNoteController.addGrn(grn);
            util.Utilities.showMsgBox("GRN added successfully", "Grn Success", 0);
            this.dispose();
        } catch (SQLException ex) {
            util.Utilities.showMsgBox("Unable to add grn", "Grn Error", 0);
            logger.error(ex.getMessage());
        }
    }

    // </editor-fold>
    //
    //
    // <editor-fold defaultstate="collapsed" desc="Interface Management">
    private void initInterface() {
        try {
            for (Supplier s : SupplierController.getAllSuppliers()) {
                comboSupplier.addItem(s);
            }
        } catch (SQLException ex) {
            logger.error("Error: " + ex.getMessage());
        }

        // Add stores here
        comboLocation.addItem("stores");

        // Add payment methods here
        comboPaymentType.addItem("cheque");
        comboPaymentType.addItem("cash");
        comboPaymentType.addItem("credit");

        try {
            txtF16aNumber.setText(GoodRecieveNoteController.getNextGrnID());
        } catch (SQLException ex) {
            logger.error("Error: " + ex.getMessage());
        }

        datePickInvoiceDate.setDate(util.Utilities.getToday());

        ((PlainDocument) txtLoadingFee.getDocument()).setDocumentFilter(new CurrencyFilter());
        ((PlainDocument) txtPurchasingBillDiscount.getDocument()).setDocumentFilter(new CurrencyFilter());
        ((PlainDocument) txtSellingBillDiscount.getDocument()).setDocumentFilter(new CurrencyFilter());
    }

    // </editor-fold>
    //
    //
    // <editor-fold defaultstate="collapsed" desc="Item Management">
    public static boolean isItemValid(int row, DefaultTableModel model) {
        Boolean out = true;
        if (row >= 0 && row < model.getRowCount()) {
            try {
                if (ProductController.getProduct("p" + model.getValueAt(row, 1).toString()) == null) {
                    out = false;
                }
            } catch (SQLException ex) {
                model.setValueAt("", row, 1);
                out = false;
            }

            if (util.Utilities.getDateFromString(model.getValueAt(row, 5).toString()) == null) {
                // util.Utilities.ShowWarningMsg(null, "Enter a valid date");
                out = false;
            }

            try {
                if (Double.parseDouble(model.getValueAt(row, 4).toString()) < 0) {
                    out = false;
                }
            } catch (Exception ex) {
                out = false;
            }

            try {
                if (Double.parseDouble(model.getValueAt(row, 4).toString()) > 100) {
                    out = false;
                }
            } catch (Exception ex) {
                out = false;
            }

            int[] checkInt = new int[]{3, 6, 7, 8};
            for (int column : checkInt) {
                try {
                    if (Double.parseDouble(model.getValueAt(row, column).toString()) < 0) {
                        out = false;
                    }
                } catch (Exception ex) {
                    out = false;
                }
            }

            try {
                if (Double.parseDouble(model.getValueAt(row, 7).toString()) < Double.parseDouble(model.getValueAt(row, 8).toString())) {
                    out = false;
                }
            } catch (Exception ex) {
                out = false;
            }

            return out;
        }
        return out;
    }

    public static boolean isItemValidWithChanges(int row, DefaultTableModel model) {
        Boolean out = true;
        if (row >= 0 && row < model.getRowCount()) {
            try {
                if (ProductController.getProduct("p" + model.getValueAt(row, 1).toString()) == null) {
                    model.setValueAt("", row, 1);
                    out = false;
                }
            } catch (SQLException ex) {
                model.setValueAt("", row, 1);
                out = false;
            }

            if (util.Utilities.getDateFromString(model.getValueAt(row, 5).toString()) == null) {
                model.setValueAt(util.Utilities.getStringDate(util.Utilities.getCurrentDate()), row, 5);
                // util.Utilities.ShowWarningMsg(null, "Enter a valid date");
                out = false;
            }

            try {
                if (Double.parseDouble(model.getValueAt(row, 4).toString()) < 0) {
                    model.setValueAt(0, row, 4);
                    out = false;
                }
            } catch (Exception ex) {
                model.setValueAt(0, row, 4);
                out = false;
            }

            try {
                if (Double.parseDouble(model.getValueAt(row, 4).toString()) > 100) {
                    model.setValueAt(100, row, 4);
                    out = false;
                }
            } catch (Exception ex) {
                model.setValueAt(100, row, 4);
                out = false;
            }

            int[] checkInt = new int[]{3, 6, 7, 8};
            for (int column : checkInt) {
                try {
                    if (Double.parseDouble(model.getValueAt(row, column).toString()) < 0) {
                        model.setValueAt(0, row, column);
                        out = false;
                    }
                } catch (Exception ex) {
                    model.setValueAt(0, row, column);
                    out = false;
                }
            }

            try {
                if (Double.parseDouble(model.getValueAt(row, 7).toString()) < Double.parseDouble(model.getValueAt(row, 8).toString())) {
                    model.setValueAt(Double.parseDouble(model.getValueAt(row, 7).toString()), row, 8);
                    out = false;
                }
            } catch (Exception ex) {
                model.setValueAt(0, row, 8);
                out = false;
            }

            return out;
        }
        return out;
    }

    private void addNewItem() {
        if (model.getRowCount() == 0 || isItemValid(model.getRowCount() - 1, model)) {
            model.addRow(new Object[]{model.getRowCount() + 1, 0, "", 0, 0, util.Utilities.getStringDate(util.Utilities.getCurrentDate()), 0, 0, 0, 0, 0});
        }
    }

    public void addNewItem(Product pid) {
        if (model.getRowCount() == 0 || isItemValid(model.getRowCount() - 1, model)) {
            model.addRow(new Object[]{model.getRowCount() + 1, util.Utilities.convertKeyToInteger(pid.getProductId()), pid.getProductName(), 0, 0, "", 0, 0, 0, 0, 0});
        }
    }

    private void deleteItem() {
        if (itemDataTable.getSelectedRow() >= 0 && itemDataTable.getSelectedRow() < model.getRowCount()) {
            model.removeRow(itemDataTable.getSelectedRow());
            for (int i = 0; i < model.getRowCount(); i++) {
                model.setValueAt(i + 1, i, 0);
            }
        }
    }

    private static class TableModelListenerImpl implements TableModelListener {

        private final DefaultTableModel model;

        public TableModelListenerImpl(DefaultTableModel model) {
            this.model = model;
        }

        @Override
        public void tableChanged(TableModelEvent e) {
            this.model.removeTableModelListener(this);
            for (int row = 0; row < model.getRowCount(); row++) {
                try {
                    GRNInterface.isItemValidWithChanges(row, model);
                    if (e.getColumn() == 1) {
                        // Auto generated Column
                        String productId = "P" + model.getValueAt(row, 1).toString();
                        fillProductDetails(row, productId);
                    } else if (e.getColumn() != 9 && e.getColumn() != 10) {
                        // Auto generated Column
                        Double result = Double.parseDouble(model.getValueAt(row, 3).toString()) * Double.parseDouble(model.getValueAt(row, 7).toString());
                        model.setValueAt(result.toString(), row, 9);
                        // Auto generated Column
                        result = Double.parseDouble(model.getValueAt(row, 7).toString()) * Double.parseDouble(model.getValueAt(row, 6).toString());
                        model.setValueAt(result.toString(), row, 10);
                    }
                    // model.fireTableCellUpdated(row, 8);/;
                } catch (Exception ex) {

                }
            }
            this.model.addTableModelListener(this);
        }

        private void fillProductDetails(int row, String productId) {
            Product result;
            try {
                result = ProductController.getProduct(productId);
                if (result == null) 
                model.setValueAt("", row, 2);
                else
                model.setValueAt(result.getProductName(), row, 2);
            } catch (SQLException ex) {
                logger.error(ex.getMessage());
                model.setValueAt("", row, 2);
            } finally {
                try {
                    DBConnection.closeConnectionToDB();
                } catch (SQLException ex) {
                    logger.error(ex.getMessage());
                }
            }
        }
    }

    // </editor-fold>
    //
}
