/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.view.credit;

import controller.credit.EmployeeController;
import controller.pos.UserController;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.creditManagement.Employee;
import model.people.User;
import net.proteanit.sql.DbUtils;
import util.Utilities;

/**
 *
 * @author HP
 */
public class ManageUsers extends javax.swing.JFrame {
    DefaultComboBoxModel  addUserFullNameComboBox1Model ;  
    private HashMap<Integer, Employee> employees;/**
     * Creates new form ManageEmployees
     */
    public ManageUsers() {
        initComponents();
        addUserFullNameComboBox1Model = (DefaultComboBoxModel)addUserUserLevelComboBox1.getModel();
    }
     public  void loadDetails() throws SQLException {

           addUserFullNameComboBox1Model.removeAllElements();
        ArrayList<Employee> employeeDetails = EmployeeController.loadEmployees();

        for (Employee employee : employeeDetails) {
           employees.put(employee.getEmployeeId(), employee);
            addUserFullNameComboBox1Model.addElement(employee.getEmployeeName());
        }

    }

    public void addUser() throws SQLException {
//checkvalidations
        boolean r = false;
        if(!addUserUserNameTxt1.getText().isEmpty()){
            if(!addUserPasswordTxt.getPassword().toString().isEmpty()){
                if(addUserFullNameComboBox1Model.getSelectedItem()!=null){
                    
                    UserController.addUser(new User(addUserUserNameTxt1.getText(), addUserPasswordTxt.getPassword().toString(), addUserUserLevelComboBox1.getSelectedItem().toString(),false));

                }
                else{
                     Utilities.showMsgBox("Fill all the details", "WARNING", JOptionPane.WARNING_MESSAGE);
                     r=true;
               
                }
                if(r==false){
                     Utilities.showMsgBox("Select a row to delete details", "WARNING", JOptionPane.WARNING_MESSAGE);
                     r=true;
                }
                
            }
            if(r==false){
                     Utilities.showMsgBox("Select a row to delete details", "WARNING", JOptionPane.WARNING_MESSAGE);
                     r=true;
                }
            
        
        
        }
       /* Object[] ob = {
            addUserFullNameComboBox1.getSelectedItem().toString(),
            addUserUserNameTxt1.getText(),
            addUserPasswordTxt1.getPassword(),
            
            addUserUserLevelComboBox1.getSelectedItem().toString(),};
        User newUser = new User(ob[0].toString(), ob[1].toString(),ob[2].toString(), ob[3].toString(), false);
        int employeeId = 0;
        employeeId = employees.get(ob[0].toString()).getEmployeeId();
        UserController.setDetails(newUser, employeeId);
        chngTblModel();
        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "manageUsers");
        try {
            addUser();
        } catch (SQLException ex) {
            Logger.getLogger(ManageUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
        addUserOnlineUsersTxt1.setText(null);
        addUserUserNameTxt1.setText(null);
        addUserPasswordTxt1.setText(null);*/
        
        
    }

    public void chngTblModel() throws SQLException {

  //      userTable.setModel(DbUtils.resultSetToTableModel(UserController.loadDetails()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        parentPanel = new javax.swing.JPanel();
        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        taskPaneSearchUserBtn = new javax.swing.JButton();
        jXTaskPane2 = new org.jdesktop.swingx.JXTaskPane();
        taskPaneUserDetailsBtn = new javax.swing.JButton();
        taskPaneAddUserBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        cardPanel = new javax.swing.JPanel();
        userSearch = new javax.swing.JPanel();
        subCardPanel = new javax.swing.JPanel();
        userSearchPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        userSearchUserNameLbl = new javax.swing.JLabel();
        userSeachUserSearchBtn = new javax.swing.JButton();
        userSearchUserNameTxt = new javax.swing.JTextField();
        customerSearchLBl2 = new javax.swing.JLabel();
        userSearchResultPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        userSearchResultsEmployeeIdLbl = new javax.swing.JLabel();
        UserDetailsFullNameLbl = new javax.swing.JLabel();
        userSearchUserName = new javax.swing.JLabel();
        userDeatilsUserLevelLbl = new javax.swing.JLabel();
        userDetailsAdministratorRadioBtn = new javax.swing.JRadioButton();
        userDetailsManagerRadioBtn = new javax.swing.JRadioButton();
        userDetailsEmployeeIdTxt = new javax.swing.JLabel();
        userDetailsUserNamelTxt = new javax.swing.JLabel();
        userDetailsUserNameTxt = new javax.swing.JLabel();
        userDetailsLevel1RadioBtn = new javax.swing.JRadioButton();
        installmentPaymentLbl2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        addUserPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addUserActivateBtn1 = new org.jdesktop.swingx.JXButton();
        addUserUserNameLbl2 = new javax.swing.JLabel();
        addUserPasswordLbl2 = new javax.swing.JLabel();
        addUserUserLevelLbl2 = new javax.swing.JLabel();
        addUserOnlineUsersLbl2 = new javax.swing.JLabel();
        addUserUserNameTxt1 = new javax.swing.JTextField();
        addUserUserLevelComboBox1 = new javax.swing.JComboBox();
        jScrollPane6 = new javax.swing.JScrollPane();
        addUserOnlineUsersTxt1 = new javax.swing.JTextArea();
        customerSearchLBl = new javax.swing.JLabel();
        addUserPasswordTxt = new javax.swing.JPasswordField();
        manageUsersPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        userTable = new org.jdesktop.swingx.JXTable();
        manageUserEditPanel = new javax.swing.JPanel();
        editUserBtn3 = new org.jdesktop.swingx.JXButton();
        deleteUserBtn3 = new org.jdesktop.swingx.JXButton();
        customerSearchLBl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jXTaskPaneContainer1.setBackground(new java.awt.Color(102, 102, 102));
        jXTaskPaneContainer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jXTaskPane1.setTitle("Search");
        jXTaskPane1.getContentPane().setLayout(new org.jdesktop.swingx.VerticalLayout());

        taskPaneSearchUserBtn.setText("Search User");
        taskPaneSearchUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskPaneSearchUserBtnActionPerformed(evt);
            }
        });
        jXTaskPane1.getContentPane().add(taskPaneSearchUserBtn);

        jXTaskPane2.setTitle("Manage Users");
        jXTaskPane2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        taskPaneUserDetailsBtn.setText("User Details");
        taskPaneUserDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskPaneUserDetailsBtnActionPerformed(evt);
            }
        });
        jXTaskPane2.getContentPane().add(taskPaneUserDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 10, 126, -1));

        taskPaneAddUserBtn.setText("Add User");
        taskPaneAddUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskPaneAddUserBtnActionPerformed(evt);
            }
        });
        jXTaskPane2.getContentPane().add(taskPaneAddUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 35, 126, -1));

        javax.swing.GroupLayout jXTaskPaneContainer1Layout = new javax.swing.GroupLayout(jXTaskPaneContainer1);
        jXTaskPaneContainer1.setLayout(jXTaskPaneContainer1Layout);
        jXTaskPaneContainer1Layout.setHorizontalGroup(
            jXTaskPaneContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTaskPaneContainer1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXTaskPaneContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXTaskPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXTaskPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                .addContainerGap())
        );
        jXTaskPaneContainer1Layout.setVerticalGroup(
            jXTaskPaneContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXTaskPaneContainer1Layout.createSequentialGroup()
                .addComponent(jXTaskPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jXTaskPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        cardPanel.setLayout(new java.awt.CardLayout());

        userSearch.setPreferredSize(new java.awt.Dimension(619, 551));
        userSearch.setLayout(new java.awt.BorderLayout());

        subCardPanel.setLayout(new java.awt.CardLayout());

        userSearchPanel.setToolTipText("");
        userSearchPanel.setName("paymentHistory");
        userSearchPanel.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userSearchUserNameLbl.setText("User  Name");

        userSeachUserSearchBtn.setText("Search");
        userSeachUserSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSeachUserSearchBtnActionPerformed(evt);
            }
        });

        userSearchUserNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userSearchUserNameTxtActionPerformed(evt);
            }
        });

        customerSearchLBl2.setBackground(new java.awt.Color(204, 204, 204));
        customerSearchLBl2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerSearchLBl2.setText("Search");
        customerSearchLBl2.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        customerSearchLBl2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(userSearchUserNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(customerSearchLBl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 73, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userSeachUserSearchBtn)
                            .addComponent(userSearchUserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(customerSearchLBl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userSearchUserNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userSearchUserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(userSeachUserSearchBtn)
                .addContainerGap())
        );

        userSearchPanel.add(jPanel1, new java.awt.GridBagConstraints());

        subCardPanel.add(userSearchPanel, "userSearch");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userSearchResultsEmployeeIdLbl.setText("Employee Id");

        UserDetailsFullNameLbl.setText("Full Name");

        userSearchUserName.setText("User Name");

        userDeatilsUserLevelLbl.setText("User Level");

        buttonGroup1.add(userDetailsAdministratorRadioBtn);
        userDetailsAdministratorRadioBtn.setText("Administrator");

        userDetailsManagerRadioBtn.setText("Manager");

        buttonGroup1.add(userDetailsLevel1RadioBtn);
        userDetailsLevel1RadioBtn.setText("Level 1");

        installmentPaymentLbl2.setBackground(new java.awt.Color(204, 204, 204));
        installmentPaymentLbl2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        installmentPaymentLbl2.setText("User Details");
        installmentPaymentLbl2.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        installmentPaymentLbl2.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(userDeatilsUserLevelLbl)
                        .addGap(43, 43, 43)
                        .addComponent(userDetailsManagerRadioBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userDetailsAdministratorRadioBtn)
                        .addGap(68, 68, 68)
                        .addComponent(userDetailsLevel1RadioBtn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(userSearchUserName)
                        .addGap(40, 40, 40)
                        .addComponent(userDetailsUserNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(userSearchResultsEmployeeIdLbl)
                        .addGap(381, 381, 381)
                        .addComponent(userDetailsEmployeeIdTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(UserDetailsFullNameLbl)
                        .addGap(46, 46, 46)
                        .addComponent(userDetailsUserNamelTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(installmentPaymentLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(installmentPaymentLbl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userSearchResultsEmployeeIdLbl)
                    .addComponent(userDetailsEmployeeIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserDetailsFullNameLbl)
                    .addComponent(userDetailsUserNamelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(userSearchUserName)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(userDetailsUserNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(userDetailsManagerRadioBtn))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userDetailsAdministratorRadioBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userDeatilsUserLevelLbl)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userDetailsLevel1RadioBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {UserDetailsFullNameLbl, userDeatilsUserLevelLbl, userDetailsEmployeeIdTxt, userDetailsUserNameTxt, userDetailsUserNamelTxt, userSearchResultsEmployeeIdLbl, userSearchUserName});

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout userSearchResultPanelLayout = new javax.swing.GroupLayout(userSearchResultPanel);
        userSearchResultPanel.setLayout(userSearchResultPanelLayout);
        userSearchResultPanelLayout.setHorizontalGroup(
            userSearchResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userSearchResultPanelLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(userSearchResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(userSearchResultPanelLayout.createSequentialGroup()
                    .addGap(0, 306, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 306, Short.MAX_VALUE)))
        );
        userSearchResultPanelLayout.setVerticalGroup(
            userSearchResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userSearchResultPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
            .addGroup(userSearchResultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(userSearchResultPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        subCardPanel.add(userSearchResultPanel, "userSearchResult");

        userSearch.add(subCardPanel, java.awt.BorderLayout.CENTER);

        cardPanel.add(userSearch, "userSearchDetails");

        addUserPanel.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        addUserActivateBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addUserActivateBtn1.setText("Activate");
        addUserActivateBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActivateBtn1ActionPerformed(evt);
            }
        });

        addUserUserNameLbl2.setText("User Name");

        addUserPasswordLbl2.setText("Password");

        addUserUserLevelLbl2.setText("User Level");

        addUserOnlineUsersLbl2.setText("Online Users");

        addUserUserNameTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserUserNameTxt1ActionPerformed(evt);
            }
        });

        addUserUserLevelComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Cashier", "Inventory" }));
        addUserUserLevelComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserUserLevelComboBox1ActionPerformed(evt);
            }
        });

        addUserOnlineUsersTxt1.setColumns(20);
        addUserOnlineUsersTxt1.setRows(5);
        jScrollPane6.setViewportView(addUserOnlineUsersTxt1);

        customerSearchLBl.setBackground(new java.awt.Color(204, 204, 204));
        customerSearchLBl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerSearchLBl.setText("Add User");
        customerSearchLBl.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        customerSearchLBl.setOpaque(true);

        addUserPasswordTxt.setText("jPasswordField1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerSearchLBl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addUserUserLevelLbl2)
                            .addComponent(addUserPasswordLbl2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addUserUserLevelComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addUserPasswordTxt)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(addUserUserNameLbl2)
                        .addGap(26, 26, 26)
                        .addComponent(addUserUserNameTxt1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addUserActivateBtn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(addUserOnlineUsersLbl2)
                                .addGap(14, 14, 14)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(customerSearchLBl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserUserNameLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserUserNameTxt1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserPasswordLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserPasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserUserLevelLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserUserLevelComboBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUserOnlineUsersLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addUserActivateBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        addUserPanel.add(jPanel2, new java.awt.GridBagConstraints());
        jPanel2.getAccessibleContext().setAccessibleParent(cardPanel);

        cardPanel.add(addUserPanel, "addUser");

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Full Name", "User  Name", "User Level "
            }
        ));
        userTable.setShowGrid(true);
        jScrollPane7.setViewportView(userTable);

        manageUserEditPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        editUserBtn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editUserBtn3.setText("Edit");
        editUserBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUserBtn3ActionPerformed(evt);
            }
        });

        deleteUserBtn3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteUserBtn3.setText("Delete");
        deleteUserBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout manageUserEditPanelLayout = new javax.swing.GroupLayout(manageUserEditPanel);
        manageUserEditPanel.setLayout(manageUserEditPanelLayout);
        manageUserEditPanelLayout.setHorizontalGroup(
            manageUserEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUserEditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageUserEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editUserBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteUserBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                .addContainerGap())
        );
        manageUserEditPanelLayout.setVerticalGroup(
            manageUserEditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageUserEditPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(editUserBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteUserBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        customerSearchLBl1.setBackground(new java.awt.Color(204, 204, 204));
        customerSearchLBl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        customerSearchLBl1.setText("Manage User");
        customerSearchLBl1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        customerSearchLBl1.setOpaque(true);

        javax.swing.GroupLayout manageUsersPanelLayout = new javax.swing.GroupLayout(manageUsersPanel);
        manageUsersPanel.setLayout(manageUsersPanelLayout);
        manageUsersPanelLayout.setHorizontalGroup(
            manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageUsersPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(customerSearchLBl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageUserEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        manageUsersPanelLayout.setVerticalGroup(
            manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageUsersPanelLayout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(customerSearchLBl1)
                .addGap(12, 12, 12)
                .addGroup(manageUsersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageUserEditPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        cardPanel.add(manageUsersPanel, "manageUsers");

        jPanel5.add(cardPanel);

        javax.swing.GroupLayout parentPanelLayout = new javax.swing.GroupLayout(parentPanel);
        parentPanel.setLayout(parentPanelLayout);
        parentPanelLayout.setHorizontalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        parentPanelLayout.setVerticalGroup(
            parentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(parentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jXTaskPaneContainer1.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addUserActivateBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActivateBtn1ActionPerformed
        try {
            // TODO add your handling code here:
            addUser();
        } catch (SQLException ex) {
            Logger.getLogger(ManageUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_addUserActivateBtn1ActionPerformed

    private void addUserUserNameTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserUserNameTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserUserNameTxt1ActionPerformed

    private void addUserUserLevelComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserUserLevelComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addUserUserLevelComboBox1ActionPerformed

    private void taskPaneSearchUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskPaneSearchUserBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "userSearchDetails");
    }//GEN-LAST:event_taskPaneSearchUserBtnActionPerformed

    private void taskPaneAddUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskPaneAddUserBtnActionPerformed
        addUserOnlineUsersTxt1.setText(UserController.getLoggedInUsers().getUserName());
        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "addUser");
        
    }//GEN-LAST:event_taskPaneAddUserBtnActionPerformed

    private void taskPaneUserDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskPaneUserDetailsBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout) cardPanel.getLayout();
        card.show(cardPanel, "manageUsers");
    }//GEN-LAST:event_taskPaneUserDetailsBtnActionPerformed

    private void editUserBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUserBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editUserBtn3ActionPerformed

    private void deleteUserBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteUserBtn3ActionPerformed

    private void userSearchUserNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSearchUserNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userSearchUserNameTxtActionPerformed

    private void userSeachUserSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userSeachUserSearchBtnActionPerformed
        // TODO add your handling code here:
        CardLayout card2 = (CardLayout) subCardPanel.getLayout();
        card2.show(cardPanel, "userSearchResult");
    }//GEN-LAST:event_userSeachUserSearchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUsers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUsers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserDetailsFullNameLbl;
    private org.jdesktop.swingx.JXButton addUserActivateBtn1;
    private javax.swing.JLabel addUserOnlineUsersLbl2;
    private javax.swing.JTextArea addUserOnlineUsersTxt1;
    private javax.swing.JPanel addUserPanel;
    private javax.swing.JLabel addUserPasswordLbl2;
    private javax.swing.JPasswordField addUserPasswordTxt;
    private javax.swing.JComboBox addUserUserLevelComboBox1;
    private javax.swing.JLabel addUserUserLevelLbl2;
    private javax.swing.JLabel addUserUserNameLbl2;
    private javax.swing.JTextField addUserUserNameTxt1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JLabel customerSearchLBl;
    private javax.swing.JLabel customerSearchLBl1;
    private javax.swing.JLabel customerSearchLBl2;
    private org.jdesktop.swingx.JXButton deleteUserBtn3;
    private org.jdesktop.swingx.JXButton editUserBtn3;
    private javax.swing.JLabel installmentPaymentLbl2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane2;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private javax.swing.JPanel manageUserEditPanel;
    private javax.swing.JPanel manageUsersPanel;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JPanel subCardPanel;
    private javax.swing.JButton taskPaneAddUserBtn;
    private javax.swing.JButton taskPaneSearchUserBtn;
    private javax.swing.JButton taskPaneUserDetailsBtn;
    private javax.swing.JLabel userDeatilsUserLevelLbl;
    private javax.swing.JRadioButton userDetailsAdministratorRadioBtn;
    private javax.swing.JLabel userDetailsEmployeeIdTxt;
    private javax.swing.JRadioButton userDetailsLevel1RadioBtn;
    private javax.swing.JRadioButton userDetailsManagerRadioBtn;
    private javax.swing.JLabel userDetailsUserNameTxt;
    private javax.swing.JLabel userDetailsUserNamelTxt;
    private javax.swing.JButton userSeachUserSearchBtn;
    private javax.swing.JPanel userSearch;
    private javax.swing.JPanel userSearchPanel;
    private javax.swing.JPanel userSearchResultPanel;
    private javax.swing.JLabel userSearchResultsEmployeeIdLbl;
    private javax.swing.JLabel userSearchUserName;
    private javax.swing.JLabel userSearchUserNameLbl;
    private javax.swing.JTextField userSearchUserNameTxt;
    private org.jdesktop.swingx.JXTable userTable;
    // End of variables declaration//GEN-END:variables
}